### ISSUE TITLE
Summing 2 (multiple) columns...

### ISSUE THREAD

**Issue by luckman212** [tgrosinger/advanced-tables-obsidian#100]
I tried reading https://github.com/tgrosinger/md-advanced-tables/blob/main/docs/formulas.md a couple of times, and faffing about with it but the best I could come up with to sum 2 adjacent columns was this:

```md
| Item      | Qty | Price |
|:--------- | ---:| -----:|
| Apples    |  10 |  8.75 |
| Pears     |  -3 | -3.75 |
| Plums     |   4 |  3.22 |
| Peaches   |   2 |  2.82 |
| Raisins   |  31 |  1.13 |
| **Total** |  44 | 12.17 |
<!-- TBLFM: @>$2=sum(@I..@-1) -->
<!-- TBLFM: @>$3=sum(@I..@-1);%.2f -->
```

Is this really the best (or only) way?
Is there a way to combine these statements or chain them for efficiency?

E.g. (these don't work)
```
<!-- TBLFM: @>$2..$3=sum(@I..@-1) -->
<!-- TBLFM: @>$2=sum(@I..@-1)::@>$3=sum(@I..@-1) -->
```

Thank you @tgrosinger for any advice

**Comment by tgrosinger** [comment]
@luckman212, I think you have found the best way. The last line in your post should work, however there's a bug I haven't gotten to sorting out: https://github.com/tgrosinger/md-advanced-tables/issues/19

**Comment by luckman212** [comment]
Appreciate you taking a look, thank you @tgrosinger

**Comment by tgrosinger** [comment]
Oops, I had linked to the wrong related issue. I am going to close this ticket and let that ticket in the md-advanced-tables repo track this issue. Let me know if you feel that issue does not fully address your comment.
