### ISSUE TITLE
CSV export is not working or I can't figure out how to do it properly

### ISSUE THREAD

**Issue by shivenigma** [tgrosinger/advanced-tables-obsidian#101]
**Describe the bug**
I have the following table in one of my notes.
```
| Item                                                                 | Hours |
| -------------------------------------------------------------------- | ----- |
| Updating                                      | 0.25  |
| Reviewing a PR                                    | 0.25  |
| team call                                                   | 0.25  |
| Discussion with PRs review | 0.25  |
| implementation, analysis, and testing                    | 6     |
| Analysis for library and .                            | 1     |
| Total                                                                | 8     |
<!-- TBLFM: @>$2=sum(@I..@-1) -->
```

I tried to export it to CSV by clicking the CSV icon on the toolbar and nothing happens. I'm not sure what will happen as the docs doesn't provide much about how CSV export will work.

**To Reproduce**
1. Copy the above table in your note
2. Click on export CSV icon in table toolbar

**Expected behavior**
A CSV file will be downloaded or I'm being asked to save somewhere?

**Desktop (please complete the following information):**
 - OS: Windows
 - Obsidian Version: 0.12.10
 - Advanced Tables Version: 0.12.5

**Comment by tgrosinger** [comment]
It looks like maybe the plugin is not enabled. Otherwise I am not sure why it would not be formatted nicely.

Here's a demo of what the plugin should do to export as CSV.

![csv-export](https://user-images.githubusercontent.com/597386/127351349-b4b5dc33-ea3b-4da5-813f-421b38687a1d.gif)

**Comment by shivenigma** [comment]
Plugin is enabled. I messed up the formatting when pasting here I guess. I'll check once again and will update here.

Thanks for your wonderful work on this plugin also for taking your time to reply.

**Comment by shivenigma** [comment]
I copied the table to an empty note, and tried to export and it worked.

now I tried it in my original note again where it is mixed with other content, it worked there too.

I swear it wasn't before. Anyway, This is not a problem for me anymore.
