### ISSUE TITLE
Rounding (Float ?) Issue with sum() function.

### ISSUE THREAD

**Issue by Write** [tgrosinger/advanced-tables-obsidian#103]
**Describe the bug**
Sum() functions sometimes add maximum number of digits after the decimal pointn when is it not needed, and also adds a little value out of nowhere. I'm guessing a floating issue but i don't know much more about that.

**To Reproduce**
Copy my example table at the bottom, and evaluate it to see the bug in action.

**Expected behavior**
I expected Total Row value to be at most two digits after the decimal point, as my numbers have all a maximum of two digits after it. And even if only **one** my my number would had 3 numbers after the decimal point (e.g. 399.999) I would've expected the Total Row value to be at most tree digits after it, but never more.

Weirdly, setting TEST1 value to -7.24 which is only 0.01 less seems to work as intended.

**Screenshots**
![image](https://user-images.githubusercontent.com/541722/127778506-85f8a161-3bf0-417d-812a-255674b1b0f1.png)

**Desktop (please complete the following information):**
 - OS: Win. 10
 - Obsidian Version: v12.12
 - Advanced Tables Version: 0.13.0

**Additional context**
Copy pastable example table
```
| TEST     |               TEST |
|:-------- | ------------------:|
|          |                    |
| **TEST** |                    |
|          |                    |
| TEST     |            +396.25 |
| TEST     |             +28.75 |
|          |                    |
| TEST     |                -10 |
| TEST1    |              -7.25 |
| TEST     |                 -6 |
| TEST     |              -1.65 |
| TEST     |               -125 |
| TEST     |                -27 |
| TEST     |              -12.5 |
|          |                    |
| **TEST** |                    |
|          |                    |
|          |                 -0 |
|          |                 -0 |
|          |                 -0 |
|          |                 -0 |
| Total    | |
<!-- TBLFM: @>$2=sum(@I..@-1) -->
```

**Comment by mochsner** [comment]
@Write I believe this would likely belong in [https://github.com/tgrosinger/md-advanced-tables](https://github.com/tgrosinger/md-advanced-tables), a dependency of this project.

(Also - this is a classic javascript issue with floats. See [here](https://stackoverflow.com/questions/7540228/javascript-adds-0-000000002-to-calculation) if you'd like to look into how to do the rounding yourself. )

**Comment by tgrosinger** [comment]
You may specify the number formatting you want it to use in your formula. Instructions are [here](https://github.com/tgrosinger/md-advanced-tables/blob/main/docs/formulas.md#formatting-options).

**Comment by Write** [comment]
> 
> 
> @Write I believe this would likely belong in https://github.com/tgrosinger/md-advanced-tables, a dependency of this project.
> 
> (Also - this is a classic javascript issue with floats. See [here](https://stackoverflow.com/questions/7540228/javascript-adds-0-000000002-to-calculation) if you'd like to look into how to do the rounding yourself. )

Thanks for the inforrmation :) !

> 
> 
> You may specify the number formatting you want it to use in your formula. Instructions are [here](https://github.com/tgrosinger/md-advanced-tables/blob/main/docs/formulas.md#formatting-options).

Thanks, I should've read more thoroughly
