### ISSUE TITLE
Don't support ":"  in tables 

### ISSUE THREAD

**Issue by SUPERustam** [tgrosinger/advanced-tables-obsidian#104]
# What's Problem?
Advanced-tables-obsidian doesn't understand `:` in table.
How to use and what is it `:` in tables (Markdown): https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables

## Short explained what is bug:
If I write these characters `:`  in table for centerline content in every column and format table with advanced-tables-obsidian, I will get this:

### Before formatting:

![image](https://user-images.githubusercontent.com/64551202/128382891-e2965086-3ea1-44f8-8dc8-3d156cd3d58b.png)
![image](https://user-images.githubusercontent.com/64551202/128382934-6003431f-a1ab-4333-abc5-7ee6394929c0.png)

### After formatting:

![image](https://user-images.githubusercontent.com/64551202/128383006-92ee3b35-a6c7-4e04-a4b8-a2fbaa5e9e41.png)
![image](https://user-images.githubusercontent.com/64551202/128383032-f80b8b4f-9bc2-4c05-ab8d-3f09645f401c.png)

This is bug.

## How To Reproduce Bug?
1. Open Obsidian
2. Go to note 
3. For example, make this table:
```md
| First            | Second         | Third                   |
|: ---------------- :|: -------------- :|: -----------------------: |
| Eric (School 25) | 12             | Basketball and football |
| Nick             | 13             | Soccer                  |
| Ben              | 12 (15.6.2008) | Math                    |
``` 
4. Format this table using `1` or `2` command:

![image](https://user-images.githubusercontent.com/64551202/128384474-341edfc3-2890-4afc-b6a9-c90251b97277.png)

5. Boom! Wrong formatting (bug!)

Desktop:
 - OS: Linux Manjaro Gnome 40
 - Obsidian Version: v0.12.10 (last)
 - Advanced Tables Version: 0.13.0 (last)

P.S. I'm not a native English speaker. Pardon me for my poor choice of words :alien:

**Comment by tgrosinger** [comment]
Hello,
This is supported. Please try with this table:

```
|      First       |     Second     |          Third          |
|:----------------:|:--------------:|:-----------------------:|
| Eric (School 25) |       12       | Basketball and football |
|       Nick       |       13       |         Soccer          |
|       Ben        | 12 (15.6.2008) |          Math           |
```

It may be easier to write the table without the `:` characters, then use the alignment buttons in the top row of the toolbar.

![image](https://user-images.githubusercontent.com/597386/128893422-6ba0b2ce-ae0b-45e7-a91d-cb7c0217c5df.png)

**Comment by SUPERustam** [comment]
Thank you, @tgrosinger! I just made spaces between `: `  and  `---`. Obsidian understands this syntax, but advanced-tables-obsidian not 😢
