### ISSUE TITLE
Chinese automatic alignment is not working properly.

### ISSUE THREAD

**Issue by troilus** [tgrosinger/advanced-tables-obsidian#106]
**Describe the bug**
Chinese automatic alignment is not working properly.

**To Reproduce**
1.Input Chinese characters of different lengths
2.Press the TAB key to automatically generate the table, and press Enter to generate a new line
3.Input Chinese characters of different lengths, press TAB key to automatically generate a table
**Expected behavior**
Automatic alignment of table like column width

**Screenshots**
![image](https://user-images.githubusercontent.com/1055100/128806255-2dd8faad-4606-4a69-b468-6952671955ba.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Obsidian Version: [v0.12.12] 
 - Advanced Tables Version: [0.13.0] 

**Additional context**

**Comment by tgrosinger** [comment]
Hello, please read through issue #30 and let me know if that solve the issue for you.

**Comment by troilus** [comment]
> Hello, please read through issue #30 and let me know if that solve the issue for you.

Thanks for reply. I installed the font but there is no setting in option:
Only 4 options:
![image](https://user-images.githubusercontent.com/1055100/128959923-1c6d8e6a-422e-4c74-88d0-d5c0c7d4f3f9.png)
https://github.com/tgrosinger/advanced-tables-obsidian/issues/30 : 
![image](https://user-images.githubusercontent.com/1055100/128959956-e793ff38-fa21-4880-8b21-9c2dbff3ca36.png)

**Comment by reorx** [comment]
@troilus the option was removed, but you can use snippets to achieve that, see this link on the forum: https://forum.obsidian.md/t/monospace-font-in-the-editor/648

Here's my snippet file:

```
.markdown-source-view {
    --font-monospace: 'Sarasa Term SC', 'Sarasa Term TC', monospace;
}
```

**Comment by tgrosinger** [comment]
Thanks for the comment @reorx. I'm going to close this one, but reopen if there's any more issues.
