### ISSUE TITLE
Table controls toolbar : buttons don't do anything

### ISSUE THREAD

**Issue by Elaws** [tgrosinger/advanced-tables-obsidian#110]
**Describe the bug**
Table controls toolbar (Ctrl + Shift + D) doesn't seem to work anymore. Its buttons don't do anything (deleting a row, sort alphabetically, etc...).

**To Reproduce**
1. Go to "Help" vault.
2. Disable "Safe Mode".
3. Install Advanced Tables plugin.
4. Create a new note.
5. Create a table.
6. Display "Table controls toolbar" and click on any of its buttons : nothing happens.

**Expected behavior**
Each button should react according to its description.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version: 0.12.12
 - Advanced Tables Version: 0.13.0

**Comment by willdhorn** [comment]
If anyone else having this issue comes accross this, I was able to fix it by just restarting Obsidian.
