### ISSUE TITLE
Can't access to Advanced Table Toolbar

### ISSUE THREAD

**Issue by NewbieObsidian** [tgrosinger/advanced-tables-obsidian#111]
Hi,

First of all, thanks for this plugin that is helping me and going to still helping a lot.

I got a problem that i can't find answer in forums : 
I'm on windows, did follow installation instruction, can make table with "enter" and "tab", but i can't oppened, neither by hotkey neither by Ctrl + P command or by clicking on the menu button.

i've seen @Elaws having the same issue, the issue looks to be "closed" but i did not find the answer.

Thanks for your help,

Best regards

**Comment by NewbieObsidian** [comment]
Ok my bad, i found where the tool was, in an small open windows at the side...

But anyway, still get a problem, the actions seems to work on edit mode (like centered column) but dosen't not affect the preview mode

Thx,

**Comment by tgrosinger** [comment]
Can you please share your table and a screenshot so I can see what you mean by not affecting the preview?

**Comment by NewbieObsidian** [comment]
Oh, i'm gonna be expelled... i should have tried everything before bothering you...

I found the problem : The plugin was in conflict with my CSS table note, as i put "text-align: left;"

To summarise : 
- The toolbar doesn't show in the editing mode but in another panel at the side so it's not really a problem
- The action of the toolbar are possibly in conflict with CSS notes as the CSS is hierarchically the first used by Obsidian

Well, again, sorry for bothering you, i'm glad i've find the solution anyway.

Best regards
