### ISSUE TITLE
Render checkboxes in tables

### ISSUE THREAD

**Issue by johans3** [tgrosinger/advanced-tables-obsidian#113]
**Describe the bug**
Checkboxes aren't rendered correctly inside tables, unlike outside tables

**To Reproduce**
1. In edit more, enter: | - [ ] A | 
2. Press tab
3. Switch to preview mode

**Expected behavior**
I've tried to resolve with css and got blue checkboxes in table view and violet checkboxes outside tables. I don't know anything about css and feel not comfortable to use my own experimental code

**Desktop (please complete the following information):**
 - OS:  Android
 - Obsidian Version:  0.12.15
 - Advanced Tables Version: 0.13.0

**Comment by tgrosinger** [comment]
Hello, this plugin is only focused on how tables are edited, not how they are rendered. This sounds like a bug that should be reported to the Obsidian developers.
Thanks!
