### ISSUE TITLE
Hide cell grid lines

### ISSUE THREAD

**Issue by johans3** [tgrosinger/advanced-tables-obsidian#114]
**Is your feature request related to a problem? Please describe.**
Im looking for a way to arrange pictures and text in a simple and quick way and tables are suitable for this task, but cell grid lines are superfluous and disturbing in preview mode

**Describe the solution you'd like**
Basically, my request is to hide cell grid lines in preview mode and printing. This way we can arrange picture(s) and their description in a fast and flexible way

**Describe alternatives you've considered**
Currently I'm using `image flags.css` and it's easy to use, but I want to use tables whenever possible and to combine text and images in configurations, arrangements I like

**Comment by tgrosinger** [comment]
Hello, thank you for the suggestion. This plugin is only focused on the editing of tables, so it is not able to change how tables are rendered when previewing or printing. Sorry about that.
