### ISSUE TITLE
Feature: One-click duplicate row or column

### ISSUE THREAD

**Issue by MavropaliasG** [tgrosinger/advanced-tables-obsidian#115]
With one click it adds a new row or column (different buttons) and copies the contents of the existing one.

**Comment by tgrosinger** [comment]
Hi @MavropaliasG, thanks for the suggestion. This plugin already has a ton of commands, so I need to be pretty judicious about adding new ones. This seems like feature that could either be non-table specific (duplicate any line) or through existing features (in vim mode, use `yyp`).
