### ISSUE TITLE
Table formatting breaks when using Markdown Blockquotes

### ISSUE THREAD

**Issue by dipeshkd** [tgrosinger/advanced-tables-obsidian#122]
**Describe the bug**
Placing tables under Blockquote breaks the autoformatting however table navigation (tab/enter) are working fine

**To Reproduce**
1. Create Markdown Blockquote with ">"
2. go to new line. Ensure that ">" is not present. Obsidian puts anything directly under ">" inside the Blockquote
3. start creating the table.
4. table is created as normal however it is not formatted correctly in edit mode.
5. table is rendered correctly

**Expected behavior**
Table should be formatted as normal

**Screenshots**
Screenshot 1 - Edit
- first table is the example of formatted table
- second table is the same table under Blockquote
![image](https://user-images.githubusercontent.com/9581711/138423522-7d2b7500-76c6-4d3e-8779-d48151339231.png)

Screenshot 2 - Preview
This shows the rendering of the table
![image](https://user-images.githubusercontent.com/9581711/138423841-d39a61e7-ddf8-4861-8919-d4b2c0c32cfc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version: v0.12.19
 - Advanced Tables Version: 0.13.0

**Comment by tgrosinger** [comment]
Hello,
This issue is caused by Obsidian switching fonts used when the table is in a blockquote. The font is no longer monospaced, so it appears to be malformatted, even though it is using the correct amount of padding.

**Comment by dipeshkd** [comment]
Hi @tgrosinger, Thanks, I was able to find a solution based on your comments. 

For anyone that is interested, you need to change the font type that is being used by Obsidian. This can be done by using a custom CSS.

Below are the Steps that can be followed which I based on [Obsidian forum](https://forum.obsidian.md/t/how-to-change-font/10927) on how to change fonts:

I am using CaskaydiaCove NF which can be downloaded from [here](https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/CascadiaCode.zip). You can use your own.

1. Click 'Settings' and go to 'Appearance'
2. Under the 'CSS snippets' click the 'Open snippets folder' 
3. Create a 'New Text Document' and rename it to 'fontstyle.css' (you can create your own name)
4. Open the document and paste the following code and save the file. This should only affect the font in the 'Edit view'. 
      ```css
      .markdown-source-view {
          font-family: 'CaskaydiaCove NF';
        }
      ```
    To change the font both in both Edit and Preview view, you can follow the code shared by 'Genzer' in the Obsidian forum link shared above.
5. In Obsidian, back to 'Appearance' toggle on the CSS that you just created and click on 'Reload snippets'
![Obsidian_6A6H6uwZ5c](https://user-images.githubusercontent.com/9581711/143721077-a8cd04cf-2a6c-4c97-b623-76fbda98c941.png)
6. This should activate the snippet and change the font.


### Results
#### Before the change 

![Obsidian_0v2INcuqPs](https://user-images.githubusercontent.com/9581711/143721146-955f9e45-2af3-4c6c-8d98-886ca8023524.png)

#### After the change

![Obsidian_BxhbZ9yaWf](https://user-images.githubusercontent.com/9581711/143721161-defa1777-72d7-44a1-89ac-dd00bb95db70.png)
