### ISSUE TITLE
Table formatting breaks if a left square bracket is in the text

### ISSUE THREAD

**Issue by RobColes** [tgrosinger/advanced-tables-obsidian#123]
Love the plugin!

Table formatting does not work correctly if a left square bracket "[" appears in the text.  I noticed this when trying to add links to a table, and also with todos. Playing around showed that closing square brackets seem OK but opening square brackets cause the problem.

**To Reproduce**
Anywhere in the table type a left square bracket and hit tab

**Expected behavior**
The left bracket should not change the way the table is formatted, it should be treated as any other character to work out spacing

**Screenshots**
![image](https://user-images.githubusercontent.com/1765065/138535401-4f912588-418a-49e4-8112-4a3a78c2c869.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version: 0.12.16
 - Advanced Tables Version: 0.13.0

**Comment by keifererikson** [comment]
I am having the same issue. Internal linking to any other notes breaks the formatting alignment. I still haven't fount a workaround yet.

**Comment by tgrosinger** [comment]
I'm not able to reproduce this in my Vault where I am using default themes and no other plugins. Please reopen this issue if you can narrow down the cause.

![image](https://user-images.githubusercontent.com/597386/143501830-0772916b-e6b9-41c4-93d8-315cbfe759b2.png)
