### ISSUE TITLE
[Feature Request] Additional lines 

### ISSUE THREAD

**Issue by moashxer** [tgrosinger/advanced-tables-obsidian#127]
#### Hi,
First of all thanks a lot for your work. 

**Is your feature request related to a problem? Please describe.**
Advanced table is very helpful compared to default table from obsidian I use table a lot and if there is feature for line breaks it would be great (i use <br\>) but it's very tough when having long lines and when i add or edit data after sometime it's very hard to handle such unformatted data

**Describe the solution you'd like**
If there's feature to add the next line below instead of next row (not continuing horizontally)
OR
something like ctrl+enter to add new line

Additonally 
It is possible parse code in table `table`, smiliarly if there's also >quotes and -checklist it would be nice. 

Thank you.

**Comment by tgrosinger** [comment]
Hi @moashxer,
Unfortunately there is not a way for me to change table syntax or rendering in preview mode. This plugin only makes formatting of them while editing a little easier.
