### ISSUE TITLE
Readable line lenght

### ISSUE THREAD

**Issue by moashxer** [tgrosinger/advanced-tables-obsidian#128]
I use obsidian with enabled readable line length, however when using table with this option enabled the table is only focused on continuing to the right side horizontally instead of the table focused on centered spanning on both left and right equally. 

This would get annoying when having large rows and columns where you'll have to keep scrolling through right side while your other data's are centered

- The first image is readable line length disabled (this how it should look even after enabling the option unfortunately it's not)

![Screenshot_20211119_142609](https://user-images.githubusercontent.com/87684755/142595484-f97f866b-c544-4245-8b43-42faa5b17cb1.png)

disabling the option
![Screenshot_20211119_142632](https://user-images.githubusercontent.com/87684755/142595555-e8011488-cd6e-4190-acaf-545b9f3b18b9.png)

Tables continues in right than center focused unlike the notes.
![Screenshot_20211119_143606](https://user-images.githubusercontent.com/87684755/142595828-844448a5-d19d-4aad-af3e-4b10fc6c95e5.png)

Thanks :)

**Comment by tgrosinger** [comment]
Hello @moashxer,
This plugin does not alter how tables are viewed in preview mode. It is only affecting the editing experience of tables. From your screenshots, it looks like you are asking about table width when rendered in preview mode, so unfortunately I can not help with that.
