### ISSUE TITLE
Ignore tables starting with -tx-

### ISSUE THREAD

**Issue by tgrosinger** [tgrosinger/advanced-tables-obsidian#133]
The [Tables Extended](https://github.com/aidenlx/table-extended) plugin adds support for MultiMarkdown in Obsidian. Because of how cells can be merged in that format, Advanced Tables improperly formats them.

Until #59 can be completed, we should at least ignore tables which have a `-tx-` immediately preceeding the first line.

**Comment by tgrosinger** [comment]
See also: https://github.com/tgrosinger/advanced-tables-obsidian/issues/119

**Comment by aidenlx** [comment]
btw, `tx` code blocks should be also ignored. It's not completely deprecated since the upcoming live preview update may need code blocks to render things in editor

**Comment by tgrosinger** [comment]
Finally got this fixed. Sorry it took so long!
