### ISSUE TITLE
Fix manifest / version

### ISSUE THREAD

**Issue by NomarCub** [tgrosinger/advanced-tables-obsidian#134]
A fresh install in the Obsidian help vault gives me this: `Version 1.4.0 (currently installed: 0.13.0)`
I can tell it's definitely not the new version by #116 still occuring.

![image](https://user-images.githubusercontent.com/5298006/144718332-de6f07be-66fa-41d2-b13d-53c9cebae1dd.png)

My existing installs also don't update.

**Comment by tgrosinger** [comment]
Hello,
Can you please clarify what the issue is that you are seeing? I'm not sure what bug you are reporting based on your comment.

**Comment by NomarCub** [comment]
Getting the plugin through the community plugin store gives me 0.13.0, not the latest 0.14.0 release. This is the case with an empty vault and also when updating from an existing install.

I'd think it's some mismatch in the manifest or something, I've seen this in other plugins.

**Comment by tgrosinger** [comment]
0.14.0 is only available when running Obsidian 0.13.0 or higher. Currently that is only available to Insiders. You should be able to update to the latest version once the Obsidian team makes the release public.
