### ISSUE TITLE
Enter press at first position of table should insert new line above table

### ISSUE THREAD

**Issue by Vuenc** [tgrosinger/advanced-tables-obsidian#135]
Hi, I would like to suggest a change in behavior for this very helpful plugin to allow inserting other content above tables.

**Is your feature request related to a problem? Please describe.**
When a file starts with a table, it is not easily possible to insert some content above the table. Pressing enter at the first position in the file does not insert a new line above the table, but goes to the next line of the table. The only way to insert content above right now is to copy a newline from somewhere else and paste it at this position.

**Describe the solution you'd like**
If the cursor is in the very first position in the table, i.e. just before the first "|", and the enter key is pressed, a new text line should be inserted above the table instead of going to the next line.

**Comment by klieret** [comment]
Hi @tgrosinger, are there any plans to implement such a feature? I think this would really be an important addition for many. For me it is pretty much a deal breaker that makes me not use as many markdown tables as I'd want.

**Comment by mardukbp** [comment]
I just tried pressing Shift+Enter and a new line was inserted above the table. If it works for you too, I think this issue can be closed.

**Comment by Vuenc** [comment]
You're right, that indeed works. Thanks for pointing it out! I'm closing this issue then.
