### ISSUE TITLE
Not sure but I don't think this works with CM6, correct?

### ISSUE THREAD

**Issue by luckman212** [tgrosinger/advanced-tables-obsidian#137]
As of [Obsidian 0.13.8 the default editor is the new CM6-based "live preview" one](https://forum.obsidian.md/t/obsidian-release-v0-13-8-insider-build/28329). 

I couldn't get Advanced Tables to do anything in these views, I just came to check/ask if that's true.

**Comment by tgrosinger** [comment]
Most of the functionality works, if you use the commands directly. Tab and Enter do not work yet for advancing to the next cell or row. You can rebind them to ctrl+tab and ctrl+enter though in the mean time. See #129 for the status on adding that functionality to the new editor.

**Comment by luckman212** [comment]
Ah, sorry. Should have searched better. Ok thanks for the workaround.
