### ISSUE TITLE
Auto formatting error when use Wiki Links

### ISSUE THREAD

**Issue by robertofgama** [tgrosinger/advanced-tables-obsidian#139]
- Hello, in first thank you for your job, helpes me a lot.

- Secondly, i have experienced a bug wen i add Wikilinks in my tables, the auto forrmating keeps a wrong padding on aligment of pipes (`|`). Like on picture anexed.

In order to try a solution i reinstaled the plugin, and try to download the updated version directly on github, but seems than have an incompatibilitiy on my obsidian version, because on plugin mananger is stuck on v.0.13.
I tred to change my instalation of obsidian from flatpak to appimage but seems than is not the problem too because it didn't work either.

![Captura_2021-12-14_17-41](https://user-images.githubusercontent.com/13243275/146079747-b189f0ef-fa83-435d-bb0c-921d54dd1806.png)

- Desktop
 - OS: Linux Manjaro 21.2rc
 - Obsidian Version: v.0.12.19 (Flatpak packed, also tryed on AppImage)
 - Advanced Tables Version: v.0.13.0

**Comment by wickercb** [comment]
+1 same issue. Thanks for the great plugin!

**Comment by tgrosinger** [comment]
I could have sworn there was already an issue for this, but I can't find it now. Thank you for creating this.

**Comment by robertofgama** [comment]
If you need logs or any type of information about it, just let me know.

> I could have sworn there was already an issue for this, but I can't find it now. Thank you for creating this.

**Comment by robertofgama** [comment]
A little update about this issue, looking for some conflict with another plugin I might be using and test some another things, i notice that on default theme the problem not happen. So maybe is something on this way, my theme than i was using is Cybertron (https://github.com/nickmilo/Cybertron)

**Comment by tgrosinger** [comment]
Hey @robertofgama, is this still an issue you are experiencing? I have not been able to reproduce it.

**Comment by robertofgama** [comment]
In theme Cybertron the problem persist. Now i am using the theme called things and i am not having more this problem, but if i try Cybertron the problem occurs again.

**Comment by tgrosinger** [comment]
Ah okay, thank you. I am guessing that theme just makes wiki links smaller. I don't think there's anything I can do to prevent that, and don't want to try to support all custom themes. Glad you found a workaround.
