### ISSUE TITLE
Context Menu in Edit Mode

### ISSUE THREAD

**Issue by tinng81** [tgrosinger/advanced-tables-obsidian#140]
First off, thank you for working and sharing this plugin. It has been a joyful experience for me to fully transition to Obsidian.

I noticed there is a context menu when editing the table in Edit Mode but I can't seem to replicate it on my PC. Is it part of the plugin?

I understand there is a Side Bar menu with the CMD+Shift+D but something like below enabled by default would be even more convenience.

![Context Menu in Edit Mode](https://user-images.githubusercontent.com/40393525/146610106-3d938034-9f84-4e6e-b084-c1d2aa0a87c7.png)
*From the Demo GIF*

**Comment by tgrosinger** [comment]
Hello,
The context menu is actually from a very old version and was since removed. It has been replaced by the sidebar.
