### ISSUE TITLE
Create "sub rows"

### ISSUE THREAD

**Issue by roytemple** [tgrosinger/advanced-tables-obsidian#144]
**Is your feature request related to a problem? Please describe.**

I get frustrated when I can't create "sub rows" in a new column when  I am trying to group things by the row on the left.

**Describe the solution you'd like**

I would like it to be possible to create this:

![image](https://user-images.githubusercontent.com/66756160/147360050-f643eb2f-846b-4880-9211-56bd0424a24c.png)

**Describe alternatives you've considered**

I have added <be> between items in the second column, but that feels like a very clumsy implementation to me.

**Additional context**

**Comment by tgrosinger** [comment]
Hi Roy,
Unfortunately this plugin does not have the ability to add new syntax for new table features. You might try out https://github.com/aidenlx/table-extended however as of right now it does not play very nice with Advanced Tables. I hope to fix that soon in #133.
