### ISSUE TITLE
[Bug] [Live Preview update] Not creating table by tapping TAB key

### ISSUE THREAD

**Issue by Pheggas** [tgrosinger/advanced-tables-obsidian#146]
**Describe the bug**
In Readme it's written i will be able to create table by entering | and then name of first column and tapping Tab key. In current version (see Obsidian Version below), it is not possible due to Preview Mode. As something like this as already been mentioned in #145 , I was aware this can happen. In this version, actually can create table with this plugin but with Enter key after the first column name not the Tab key.

With legacy mode this plugin works as described in Readme. :) 

**To Reproduce**
Wasn't able to detect what exactly it is causing. This bug might or might not show in front of every user that runs this verison.

**Expected behavior**
I think i described it clearly in bug description section.

**Screenshots**
Not really catchable by screenshot.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (20H2; 19042.1348)
 - Obsidian Version: 0.13.14
 - Advanced Tables Version: 0.15.0

**Additional context**
Nothing to enter here really.

**Comment by AVNechaev** [comment]
The same bug on latest Manjaro Linux with Obsidian v0.13.14 and Advanced Tables v.0.15.0

**Comment by Craftidore** [comment]
Same bug on Windows 11 21H2 22000.376 with Obsidian 0.13.18 and Advanced Tables v0.15.0

**Comment by tgrosinger** [comment]
I believe this was caused by #155 which is now resolved. Please reopen this issue if it persists after updating.
