### ISSUE TITLE
Sidebar buttons do not work if VIM keymapping is enabled

### ISSUE THREAD

**Issue by Tiriyon** [tgrosinger/advanced-tables-obsidian#150]
**Description:**
Sidebar buttons do not work when VIM keymapping is enabled.

**To Reproduce**
1. Go to settings > Editor > Advanced: Vim key bindings; and enable.
2. Open the advanced table plugin sidebar (`Ctrl + Shift + D`).
3. Press any button in the sidebar.
4. See that nothing is changed in table.

**Screenshots**

**Desktop:**
 - OS: WIndows 10/Linux (PopOS 21.10, AppImage).
 - Obsidian Version: v0.13.19
 - Advanced Tables Version: 0.15.0 

**Additional context**
I do run the plugin [vimrc support](https://github.com/esm7/obsidian-vimrc-support), I did not check if it creates any conflict with Advanced Tables. I did however disabled vim key bindings and found that the sidebar works when this is disabled.

Thanks a lot for this great plugin, I am now completely `:q` out of vim (not really, vim is love).

**Comment by tgrosinger** [comment]
Hi @Tiriyon, I have not been able to reproduce the bug you are reporting. Please let me know if you are able to provide more detailed repro steps. Thank you.

![ObsidianSidebar](https://user-images.githubusercontent.com/597386/149549964-806834f4-026e-42cd-b543-696917e60c8a.gif)

**Comment by tgrosinger** [comment]
Closing from inactivity.
