### ISSUE TITLE
Format all command formats non-tables

### ISSUE THREAD

**Issue by krokofant** [tgrosinger/advanced-tables-obsidian#153]
**Describe the bug**

Formatting tables will also format tables in code fences but should not.

**To Reproduce**

1. Create a file with this content
````markdown
```
Hello
| where foo
| where bar
| order by event_created_t desc
```

| Foo |
| --- |
| bar       |
````
2. Place the cursor on the real table, a "bar" is fine.
3. Ctrl+P: Format all tables in this file
4. Now the code block is wrongly changed:
````markdown
```
Hello
| where foo                     |
| ----------------------------- |
| where bar                     |
| order by event_created_t desc |
```

| Foo |
| --- |
| bar |
````

**Expected behavior**
The command should not format code inside of code blocks, especially not something that is not a markdown table.

**Desktop (please complete the following information):**
 - OS: Windows
 - Obsidian Version: 0.13.19
 - Advanced Tables Version: 0.15.10

**Comment by tgrosinger** [comment]
Duplicate of $130
