### ISSUE TITLE
there is no shortcut for go to up and down in the table

### ISSUE THREAD

**Issue by Archie-2021** [tgrosinger/advanced-tables-obsidian#154]
**Describe the bug**

there are hotkeys for going to next cell, previous cell, works well for navigating inside a table left and right, but there is non for going up/ previous row. and go to next row goes to start of the next row, which is useful for creating a new row, not much for navigating up and down. they also does the same function of creating new cells which can be frustrating

thanks

**Comment by tgrosinger** [comment]
Looks like this will need to be added to the underlying library used by this plugin.

**Comment by huyz** [comment]
Just a note: there is a hotkey for going to the next row, just not for going to the previous row

**Comment by tgrosinger** [comment]
I think the hotkey for going up and down a row is just the up and down arrow keys. I'm going to close this issue, but please let me know if there's additional nuance I'm missing.

**Comment by Archie-2021** [comment]
> I think the hotkey for going up and down a row is just the up and down arrow keys. I'm going to close this issue, but please let me know if there's additional nuance I'm missing.

It was an old issue for me. Since then I switched to use vim and this plugin works wonderfully with vim and is great compliment for it. for moving between lines/rows and cut/copying lines I just enter vim mode and use that and only use this plugin command for columns.
