### ISSUE TITLE
Table in Live Preview the same as during edit ?

### ISSUE THREAD

**Issue by Elaws** [tgrosinger/advanced-tables-obsidian#156]
See the image below : table is not being edited (cursor is below the table), however table renders as :

![XZWaTI2JD1](https://user-images.githubusercontent.com/52013479/149391927-0aecb8f1-27f6-4c4e-b3d4-adf145008f1b.png)

Instead of :

![A5AwPCqZjf](https://user-images.githubusercontent.com/52013479/149400369-ded0b20f-70b0-4e64-ae38-c3a3bd01b28c.png)

**Comment by tgrosinger** [comment]
Please see Issue #145.

**Comment by Elaws** [comment]
Thank you for your quick reply !

I'm not sure #145 is about the same issue. I meant : Is there a way to render the table like below, in Live Preview :

![A5AwPCqZjf](https://user-images.githubusercontent.com/52013479/149400230-c8142ee4-8de4-475d-a072-cdff289bf13f.png)

**Comment by Elaws** [comment]
Ok, so this is the expected behavior for the moment, until Obsidian supports it.

Thank you !
