### ISSUE TITLE
Help request for making two concurrent calculations in one column work

### ISSUE THREAD

**Issue by janpeeters70** [tgrosinger/advanced-tables-obsidian#158]
Apologies, if the Issue tracker it not the right place to ask a question like this.
I’m trying to get the following table with two calculations in one row to work.

| date       | activity             | duration |
| ---------- | -------------------- | -------- |
| 25-08-2021 | Activity 1           | 15       |
| 12-10-2021 | Activity 2           | 65       |
| 22-10-2021 | Activity 3           | 50       |
| 01-11-2021 | Activity 4           | 135      |
|            | Total in minutes     |          |
|            | Total in hours       |          |
 (for the total in minutes)
 (for the total in hours)

If I place the cursor in the last row of the third column and press the ‘fx’ button, it just returns a 0 in the third column of the last row. I might do something wrong with my formulas, but I can't seem to figure out what.
I've tried `<!-- TBLFM: @-1$3=sum(@I..@-1) -->` for the minutes sum, but that gave an error. 

Would something like this be possible? Or can these kinds of calculations only be done from one column to another?

**Comment by tgrosinger** [comment]
How about this?

```
| date       | activity         | duration |
| ---------- | ---------------- | -------- |
| 25-08-2021 | Activity 1       | 15       |
| 12-10-2021 | Activity 2       | 65       |
| 22-10-2021 | Activity 3       | 50       |
| 01-11-2021 | Activity 4       | 135      |
|            | Total in minutes | 265      |
|            | Total in hours   | 4.42     |
<!-- TBLFM: @6$>=sum(@I..@-1) -->
<!-- TBLFM: @>$>=(@-1/60);%.2f -->
```

**Comment by janpeeters70** [comment]
Thanks a lot @tgrosinger that works. 
What I forgot to mention is that this table is supposed to grow when I add additional lines with activities. I could, of course (not too much work), change the @6 value to @7 when I add an extra line, but I was wondering if there is also a way to keep the formula's the same while being able to add extra lines?

**Comment by tgrosinger** [comment]
Yeah, for some reason I couldn't get it to work with a relative reference like `@I-1$>` on the left side. It's been a long time since I added this feature, so I don't remember the details, but it seems that is not supported. Probably something that could be added if someone wants to take a look, but I don't think I will be able to add it in the near future.

**Comment by janpeeters70** [comment]
No problem. Your solution works, and in another case where I had three subsequent calculations I added them to three different columns, which does work. Thanks for your time!
