### ISSUE TITLE
Mobile toolbar is missing "Next Cell" or "Next Row" commands

### ISSUE THREAD

**Issue by lexxxel** [tgrosinger/advanced-tables-obsidian#160]
**Describe the bug**

There is no "Next Cell" or "Next Row" command on mobile. I can't find them "command menu" or in the customization options of the mobile toolbar. 

I'm taking about that section of the `README.md`:
`...however you can add the "Next Cell" and "Next Row" commands to the mobile toolbar and use them to navigate...`

**To Reproduce**
1. Use the mobile app
2. install the plugin
3. search commands

**Expected behavior**
be able to trigger autoformater on mobile

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android 11
 - Obsidian Version: 1.0.5
 - Advanced Tables Version: 0.15.0

**Additional context**

**Comment by tgrosinger** [comment]
Ah, this is probably because those commands check that your cursor is in a table before showing them. Ideally editing the toolbar would still show those ones. Let me check with Licat about that.

**Comment by tgrosinger** [comment]
Oh actually, looking at my iPhone, when I go into Settings->Mobile under "More toolbar options" I see "Advanced Tables: Go to next cell" and "Advanced Tables: Go to next row". The commands also show up in the quick menu when I have my cursor in a table.

Can you please update your plugin version to 0.17.0 and try again?

**Comment by lexxxel** [comment]
I updated to 0.17.0 but still, there is no such entry:
![Screenshot_2022-01-20-00-24-07-086_md obsidian](https://user-images.githubusercontent.com/5159138/150234534-65fb20b6-bd52-49f0-8d6f-86b1655885ba.jpg)

And
![Screenshot_2022-01-20-00-23-35-973_md obsidian](https://user-images.githubusercontent.com/5159138/150234557-e1ae014a-cd4d-4b2b-9b69-b75c69efc32f.jpg)
![Screenshot_2022-01-20-00-23-43-567_md obsidian](https://user-images.githubusercontent.com/5159138/150234564-4ff68639-bbae-49e2-b680-fc1b382a54e0.jpg)
![Screenshot_2022-01-20-00-23-51-759_md obsidian](https://user-images.githubusercontent.com/5159138/150234567-17345c8d-352d-427c-8e5f-163edec65c8a.jpg)

**Comment by AlmuthMueller** [comment]
Hello,
I have the same issue in the currently available Android mobile version
- advanced Tables 0.17.2
- os: Android 11

I want to add, that even so the Plugin is enabled I cannot see it under the Plugin Options section.

I hope this helps in finding the Bug, because this Plugin is very helpfull!

**Comment by Elaws** [comment]
Hello,

Same problem here 

Advanced Tables 0.17.2
Android 12

And as @AlmuthMueller, not available in the plugin options section.

**Comment by brandontellez** [comment]
Same issue here.
Advanced Tables 0.17.2
Android 11

Also cannot see it in the plug in options section.

**Comment by naiwok** [comment]
Same problem here.

Advanced Tables 0.17.2
IOS 15 (iPad and iPhone)

Main issue is that without these options we cannot easily 'refactor' or realign the table on mobile devices.

Great plugin though! Thanks for your work :)

**Comment by StjerneIdioten** [comment]
Same here :-(

Advanced Tables 0.17.2
Samsung Galaxy Tab S7 FE
Android 11

**Comment by arijit79** [comment]
Same here :-(

Version 0.17.2
Android version 9

**Comment by lexxxel** [comment]
> You maybe forget to enable the Plugins. ![Screenshot_2022-07-20-19-16-06-30](https://user-images.githubusercontent.com/42236775/179979745-3e3aef23-f627-4e86-a402-dc18b20d5184.jpg)

No, the issue has just been fixed, but was not closed, over time.
