### ISSUE TITLE
Plugin now messes with bullets and tab behaviour in standard context (no table) in the legacy editor

### ISSUE THREAD

**Issue by felixchenier** [tgrosinger/advanced-tables-obsidian#161]
**Describe the bug**
Pressing tab in the regular, legacy editor, makes loose focus instead of doing a tab. Also, starting a bullet list and pressing Enter to go on the next line no longer includes the bullet for the next line.

**To Reproduce**
In the legacy editor, on a blank page, write :

`- Test`

and press Enter. We should get

`- Test`
`-`

but we get

`- Test`
` `

instead.

Also, still in the legacy editor, on a blank page, press Tab. We should get a cursor <n> spaces after. Instead, the editor looses focus.**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Obsidian Version: 0.13.19
 - Advanced Tables Version: 0.17.0

**Comment by tgrosinger** [comment]
Great catch, thank you. I'll get a fix out for this shortly.

**Comment by felixchenier** [comment]
@tgrosinger Wow, that was fast! I installed the update and confirm that it now works again. Thank you very much!
