### ISSUE TITLE
.17 Not working with 13.19

### ISSUE THREAD

**Issue by spookymonster** [tgrosinger/advanced-tables-obsidian#162]
Couldn't get it to 'kick in' after typing pipe. Restarted Obsidian, still no go. Uninstalled .17 and manually reinstalled .16, and everything started working again.

**Comment by tgrosinger** [comment]
Hmm, okay this is tricky. This is because of how I am attempting to not run the plugin when the cursor is not in a table. I think instead of only running in a table I should instead prevent it from running when in a code block or math block. Let me give that a try.

**Comment by tgrosinger** [comment]
Please give this another try in 0.17.2.

**Comment by spookymonster** [comment]
working fine now. Thanks!
