### ISSUE TITLE
I can't find the other options of Advanced Table in command palette 

### ISSUE THREAD

**Issue by Rao-Jupiter** [tgrosinger/advanced-tables-obsidian#163]
**Describe the bug**

I used command palette, but I did not find the other options as the snapshot shows

![image](https://user-images.githubusercontent.com/70786042/150307447-4f2d1dc7-4793-424a-a34b-27b6b16284de.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Obsidian Version: 0.13.19
 - Advanced Tables Version: 0.17.2

**Comment by tgrosinger** [comment]
Hello, please make sure your cursor is in a table before opening the command palette. They options only show up when they are valid to use at the cursors current position.

**Comment by Rao-Jupiter** [comment]
> Hello, please make sure your cursor is in a table before opening the command palette. They options only show up when they are valid to use at the cursors current position.

Thank you!

And I think it could be better if put “Advanced Tables: Format all tables in this fileAdvanced Tables: Format all tables in this file” option on the comand palette  no need to put the cursor in a table
