### ISSUE TITLE
Strikethrew in tables causes display issues

### ISSUE THREAD

**Issue by Midnex** [tgrosinger/advanced-tables-obsidian#164]
**Describe the bug**
Inserting strike through text in any cell causes the table to display incorrectly while in edit mode.

**To Reproduce**
1. Make a table with at least 2 columns
2. In any cell add a strike through on the text

**Expected behavior**
table should continue to line up, even when sorting data within the table. Instead everything is misaligned

**Screenshots**
https://i.imgur.com/9rC2I8i.png

**Desktop (please complete the following information):**
 - OS: Linux
 - Obsidian Version: v0.13.19
 - Advanced Tables v0.17.2

**Comment by tgrosinger** [comment]
Dup of #145.
