### ISSUE TITLE
Cells merging

### ISSUE THREAD

**Issue by s18651** [tgrosinger/advanced-tables-obsidian#165]
**Is your feature request related to a problem? Please describe.**
When we use tables it is a very common thing to merge columns and rows not to duplicate some information.

**Describe the solution you'd like**
When we use ctrl+shift+d I would like to see 2 additional buttons of merging columns and rows based on what I currently have selected.

I have tried to do it manually just removing pipes but it filled table with default number of columns/rows. It also selects whole row then I want to select 2 rows one under another so it may be also some functionality to discuss if we would want to add merging (or maybe by doing it somehow else).

Thank you for great plugin, hope to have this feature this year :)

**Comment by tgrosinger** [comment]
Hello, Thanks for the suggestion. Markdown tables do not support column or row spans. Each row must have the same number of columns. There are extended versions of Markdown that do support this, however Obsidian does not support them natively, and so this plugin does not either.
