### ISSUE TITLE
Add lines in between rows

### ISSUE THREAD

**Issue by erankatz2020** [tgrosinger/advanced-tables-obsidian#166]
Hi! love this plugin.

I wonder if there's a way to add some kind of way to add lines between rows. Not automatically for all rows but where I choose to separate rows graphically.

Thanks!

**Comment by tgrosinger** [comment]
Unfortunately this plugin is not able to change how the table is rendered, so it cannot add whitespace or lines between rows. Thank you for the suggestion though.
