### ISSUE TITLE
Text Wrap

### ISSUE THREAD

**Issue by expat67** [tgrosinger/advanced-tables-obsidian#167]
Hello,
is there a way to wrap text within a cell in the table?
thank you

vadim

**Comment by kaylamillerdev** [comment]
Please add text wrapping! :begging face: I am working on making some large tables in obsidian and some of the content in those tables is quite long. Having word wrap or something that allows text wrapping would make my life easier. Thanks! (For the record, I have long tag names, so ideally i'd like to be able to stack them in a column / 2 per row within a column )
![Screenshot 2022-03-26 183958](https://user-images.githubusercontent.com/52870645/160259318-d24e97ad-0329-43b3-8936-85aa7e1aaed0.png)
![Screenshot 2022-03-26 184216](https://user-images.githubusercontent.com/52870645/160259371-8fdf26b4-532e-4428-877f-dd0cbe6a4359.png)

**Comment by tgrosinger** [comment]
Hello,
This plugin is not able to change how text is rendered in the table. It is only able to make the existing markdown syntax easier to write. Unfortunately this plugins is not able to add text wrapping in tables to Obsidian.
