### ISSUE TITLE
disable ribbon icon for control toolbar

### ISSUE THREAD

**Issue by Vinzent03** [tgrosinger/advanced-tables-obsidian#17]
**Is your feature request related to a problem? Please describe.**
I would like to be able to disable the new ribbon icon for the control toolbar. If I dont need it, it looks much cleaner.

**Describe the solution you'd like**
Add an switch in the settings tab.

**Comment by tgrosinger** [comment]
Great idea, will do.

**Comment by Vinzent03** [comment]
Thank you very much. I appreciate your work on this awesome plugin.
