### ISSUE TITLE
Freeze the first column

### ISSUE THREAD

**Issue by adxsoft** [tgrosinger/advanced-tables-obsidian#172]
Would be awesome if we could tab to other columns but leave the first column frozen in position.
This would be especially helpful where tables get very wide and have many columns and its easy get confused which row you are in.

**Comment by tgrosinger** [comment]
Hello,
This plugin is only focused on editing the markdown of a table, and does not have any impact on how the text is displayed. That sounds like an awesome feature, but is unfortunately outside of what is possible from this plugin.
