### ISSUE TITLE
Cells are misaligned when using external and internal links

### ISSUE THREAD

**Issue by pckc** [tgrosinger/advanced-tables-obsidian#174]
**Describe the bug**
Cells are misaligned when using external and internal links

**To Reproduce**
Type a link inside a cell and press tab

**Expected behavior**
The cell should align with the column

**Screenshots**
![table-issue2](https://user-images.githubusercontent.com/54250441/152907071-29cd52b4-ad8b-424c-9863-1e7ec114335e.png)
![table-issue5](https://user-images.githubusercontent.com/54250441/152907076-0bf47d77-4888-4a65-91ec-93df5de35ad0.png)
![table-issue](https://user-images.githubusercontent.com/54250441/152907079-a0b664ac-a6af-4b10-afe6-33fa0af35e5b.png)
![table-issue6](https://user-images.githubusercontent.com/54250441/152907081-1f01c73c-8492-465a-b8f8-fa517548b753.png)
![table-issue3](https://user-images.githubusercontent.com/54250441/152907082-e92b6c62-6a70-4370-9c16-0bbc07a7a68f.png)
![table-issue4](https://user-images.githubusercontent.com/54250441/152907083-d4708858-fa2f-4ff2-881e-d5eb41948995.png)

Setup
OS: Windows 10
Obsidian: v0.13.23
Advanced Tables Plugin: v0.17.2

**Additional context**
For the internal links I'm aware this is not expected behavior, but for external links I'm not sure it is a bug or expected. The cell is dimensioned based on the URL that is normally occulted by the markdown syntax

**Comment by tgrosinger** [comment]
It looks like you are using Live Preview and this is cause by #145.

**Comment by pckc** [comment]
Thank you kindly for replying. 

I was using Live Preview, the alignment issue is now solved but the markdown syntax is fully displayed such as #145.
