### ISSUE TITLE
Can't activate? 0.9.11

### ISSUE THREAD

**Issue by luckman212** [tgrosinger/advanced-tables-obsidian#18]
**Describe the bug**
Plugin is installed & enabled, but does not seem to be active...

**To Reproduce**
1. install plugin in Obs 0.9.11
2. try to use it

**Expected behavior**
extra table tools appear when cursor is in table cell

**Screenshots**
![image](https://user-images.githubusercontent.com/1992842/98288171-7389a500-1f74-11eb-8d80-c220a9423394.png)

![image](https://user-images.githubusercontent.com/1992842/98288092-50f78c00-1f74-11eb-95a4-8af45e00c12e.png)

![image](https://user-images.githubusercontent.com/1992842/98288137-640a5c00-1f74-11eb-85fd-94da5b344f5f.png)

![image](https://user-images.githubusercontent.com/1992842/98288315-ac297e80-1f74-11eb-8dd2-21fd6668ce0f.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Obsidian Version: 0.9.11
 - Advanced Tables Version: 0.5.2

**Comment by tgrosinger** [comment]
@luckman212 can you please try refreshing Obsidian, or closing and reopening the program?

There seems to be an issue with activating the plugin the first time that I have not figured out yet. Not sure if it's a problem on the plugin side or on the Obsidian side.

Let me know if that fixes it please.

**Comment by luckman212** [comment]
Thanks @tgrosinger - I did try that (sorry for not mentioning...) I tried both the `reload plugins` button here

![image](https://user-images.githubusercontent.com/1992842/98289785-b5b3e600-1f76-11eb-9f50-3fcc3a8bb896.png)

as well as a full Quit/relaunch of Obs app, but no luck sadly.

**Comment by tgrosinger** [comment]
Oh, it looks like you are using the style of tables that does not have pipes on the outside edges of the table. This plugin requires the table look like this:

```
| One | Two | Three |
| --- | --- | ----- |
|   1 |   2 |     3 |
```

See issue #9 which is about the same issue.

**Comment by luckman212** [comment]
@tgrosinger ah yes! that was it. Sorry, it's working fine now 🎉 
Now I just have to figure out how to switch my editor to a monospace font....

**Comment by tgrosinger** [comment]
Awesome, glad to hear it.
Instructions for changing the editor font are [here](https://forum.obsidian.md/t/monospace-font-in-the-editor/648/10)

**Comment by luckman212** [comment]
@tgrosinger Thanks for the tip 🚀 - I got the monospace font working quickly using this in my `obsidian.css`

```css
.markdown-source-view { font-family: 'JetBrainsMonoNL-Medium', monospace; }
```

**Comment by DutchPete** [comment]
Nothing to add to this issue, except to say that I, as a non-expert, always thought that the choice of monospace font was limited, and what there was was ugly.

Because of the need to use monospace for this plug-in I decided to look into it a bit more and discovered there are some quite nice ones that are more than acceptable as an Obs Preview font too.

I think it is important for people to realise this so they are not put off in any way when they see the monospace requirement.
