### ISSUE TITLE
Auto-formatting not working properly (with Primary theme)

### ISSUE THREAD

**Issue by DivM** [tgrosinger/advanced-tables-obsidian#180]
**Describe the bug**
Auto formatting not working properly with [Primary theme](https://github.com/ceciliamay/obsidianmd-theme-primary). I checked with a different theme ([Psium](https://github.com/GuangluWu/obsidian-pisum)) and was not facing the issue. It seems the issue is caused due to different font at play. Screenshots attached.

**To Reproduce**

**Expected behavior**
For table to be auto-formatted with appropriate spaces.

**Screenshots**

![Screenshot_Primary](https://user-images.githubusercontent.com/5836630/156837736-9025c0ef-2f3a-42f1-926c-35066b6ac0a5.png)

![Screenshot_Psium](https://user-images.githubusercontent.com/5836630/156837754-44cfd97d-0381-4133-9944-21f668329d13.png)

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Obsidian Version: v0.13.23
 - Advanced Tables Version: 0.17.2

**Additional context**

**Comment by DivM** [comment]
Just checked the theme's Github page. It seems the plugin is not supported by the theme and hence the issue.
Will add it as a feature request to the theme owner.

In the meantime, is there a CSS setting I can change (using _Style Settings_ Plugin) to update the table font to _Courier_, _Menlo_, etc, which would fix the spacing issue.

**Comment by marvinborner** [comment]
I am also interested in this. The formatting doesn't seem to work with the obsidian-minimal theme either.

**Comment by ytkimirti** [comment]
@DivM You can change the "Custom Edit Body Font" option under "Fonts & Typhography" in the Style Settings plugin. This fixed it for me

<img width="694" alt="image" src="https://user-images.githubusercontent.com/18082091/167499687-4d165136-5376-4567-ae58-717651d71589.png">
