### ISSUE TITLE
Inline Math Messing with Cell Padding

### ISSUE THREAD

**Issue by Skylar-Is-Alive** [tgrosinger/advanced-tables-obsidian#183]
**Describe the bug**
When creating inline math inside a table, the width of the cell does not stay consistent with what it should be.

**To Reproduce**
1. Create Table
2. Make an inline math expression inside the table
3. The cell width is not what it should be

**Expected behavior**
The cell width should stay the same on each row of the column

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 or Mac
 - Obsidian Version: v0.17.2
 - Advanced Tables Version: [e.g. 0.4.0] (Settings → Third-party plugin → Browse → Advanced Tables → currently installed)

**Additional context**
![Capture](https://user-images.githubusercontent.com/101557493/158147465-92defb77-d2ca-4b29-a86a-7275a23bdbbf.PNG)

**Comment by FadedController** [comment]
Same problem here. Hopefully this can be fixed :)

**Comment by tgrosinger** [comment]
Unfortunately I do not think there is much that we can do about this since the library calculating how wide each cell is does not have any way of knowing that the math formulas will be rendered into something with a different width. Sorry about that.

**Comment by LynetteCullens** [comment]
The Markdown Table Editor fixes it to an extent where its readable in source mode. After you create the table using Advance Tables, Open Markdown Table Editor and click "Update Table".
