### ISSUE TITLE
Really small QoL

### ISSUE THREAD

**Issue by Shiroifuyuki** [tgrosinger/advanced-tables-obsidian#184]
Completely innocuous, if you want to change this you could probably do it in less than a minute but you misspelled width in the explanation for "Pad cell width using spaces".

**Comment by 229c9cf0** [comment]
Could you edit the title of this to something like "Typo: with -> width in settings / Pad cell width using spaces' description"?

"Really small QoL" is non-descriptive, you need to click through to the issue to see what it's about. If the title already describes the problem, that saves time. (Not only for the dev, but also everyone else who's scrolling through the list of open issues and tries to avoid creating duplicate issues.)

**Comment by tgrosinger** [comment]
Fixed, thank you.
