### ISSUE TITLE
A problem about the toolbar bothers me

### ISSUE THREAD

**Issue by joelscp** [tgrosinger/advanced-tables-obsidian#187]
**Describe the bug**
The mobile toolbar never pop up，it  just stays in the sidebar, after Ctr + shift +D.
Even after turning off "Show icon in sidebar", rebooted Obsidian over and over again.
Someone help me

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Obsidian Version: [e.g. v0.9.10] (Settings → About → Current Version)
 - Advanced Tables Version: [e.g. 0.4.0] (Settings → Third-party plugin → Browse → Advanced Tables → currently installed)

**Additional context**

**Comment by Shurikus-crypto** [comment]
The context menu has been removed. Now only the sidebar.

#https://github.com/tgrosinger/advanced-tables-obsidian/issues/140#issue-1083629421
