### ISSUE TITLE
Kana characters mess with cell length

### ISSUE THREAD

**Issue by DorianK29** [tgrosinger/advanced-tables-obsidian#188]
**Describe the bug**
When writing in hiragana, katakana, the spacing on every cell with kana is wrong.

**To Reproduce**
try pasting any kana characters in a table, ie. じゃないです, でした,  じゃなかったです

**Screenshots**
![image](https://user-images.githubusercontent.com/80626896/162286699-7562bd7b-537a-4f82-81f9-e95279482b0f.png)
![image](https://user-images.githubusercontent.com/80626896/162286732-71c55c74-f8f3-4893-b767-22eaea46d2cf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version: 0.14.2
 - Advanced Tables Version: 0.17.3

**Comment by ashemedai** [comment]
That's an interesting one. The table, on edit mode, switches to a fixed-width font. Now, even if the Japanese would use a normal font, every kana is fixed-width by its very nature.

**Comment by tgrosinger** [comment]
Please see #30 and let me know if that help with this issue. Thank you.
