### ISSUE TITLE
Manually install

### ISSUE THREAD

**Issue by Doris1900** [tgrosinger/advanced-tables-obsidian#189]
My PC for work cannot access GitHub, could you please provide a zip for manual installation? thanks

**Comment by thediveo** [comment]
Obsidian for Android also doesn't work correctly, as so many complaints can be googled. Can you please provide manual installation instructions?

**Comment by tgrosinger** [comment]
The files needed for manual installation are included in each release. You'll need the `main.js`, `manifest.json`, and `styles.css`. https://github.com/tgrosinger/advanced-tables-obsidian/releases
