### ISSUE TITLE
Strange behavior if "Open table controls toolbar" hotkey is pressed when it's already showing

### ISSUE THREAD

**Issue by luckman212** [tgrosinger/advanced-tables-obsidian#19]
**Describe the bug**
If you activate the "Open table controls toolbar" hotkey, and then repeat the keyboard shortcut- instead of doing nothing or toggling off, a dim row of `--------------`s is inserted above the toolbar area. This repeats as many times as you press the key, until you switch to another note, or toggle edit/preview mode. The area is non-clickable.

**To Reproduce**
1. Make table
2. click into table
3. hit hotkey (<kbd>⌘D</kbd> in my case - I have customized it, but also tested with the default <kbd>⇧⌘D</kbd>)
4. toolbar opens
5. press hotkey again, and keep pressing it

**Expected behavior**
Toolbar should either do nothing, or toggle closed if hotkey is activated when already showing.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Obsidian Version: v0.9.11
 - Advanced Tables Version: 0.5.2

Screen recording ([open larger](https://user-images.githubusercontent.com/1992842/98301542-edc42480-1f88-11eb-8417-537d8a47a61a.gif))
![tables](https://user-images.githubusercontent.com/1992842/98301542-edc42480-1f88-11eb-8417-537d8a47a61a.gif)

**Comment by mrDLSable** [comment]
Confirmed on this setup:
OS: Windows 10 (1909)
Obsidian: v0.9.10
AT: v0.5.2

The bug also occurs when pressing the Advanced Tables Toolbar button in the sidebar.

**Comment by mrDLSable** [comment]
Pressing the close toolbar button does NOT remove these weird artifacts

**Comment by tgrosinger** [comment]
Thank you both for the issue report. Should be solved in the next release.
