### ISSUE TITLE
Akin to #188 and #191; use of links disrupts cell spacing

### ISSUE THREAD

**Issue by vlaufer** [tgrosinger/advanced-tables-obsidian#195]
**Describe the bug**
Inclusion of a link using the [[ ]] feature inherent to obsidian results in a table with non-uniform column widths.

**To Reproduce**
1. Make a table
2. Make a separate note with a link to it, e.g. a note called ABCD
3. Within the table change ABCD to [[ABCD]]
4. Visual behavior as below:

**Screenshots**
![Obsidian_Fmt](https://user-images.githubusercontent.com/42915413/168344523-cca84fc9-eb8d-4688-9244-ffc27178b6d9.png)

**Additional context**
Because there are several related, outstanding issues, I wanted to suggest that there is likely 1 fix to all these issues.

**Comment by Shirobachi** [comment]
Same for bold `**x**`, code, underline and everything what are not just simple text

**Comment by tgrosinger** [comment]
Please see #145 which discusses this issue.
