### ISSUE TITLE
Complex tables by merging cells

### ISSUE THREAD

**Issue by mafsi** [tgrosinger/advanced-tables-obsidian#20]
**Is your feature request related to a problem? Please describe.**
Can we have merge cells?

**Describe the solution you'd like**
Ability to merge cells for complex tables

**Describe alternatives you've considered**
1. https://web.archive.org/web/20170905052152/http://fletcher.github.io/MultiMarkdown-5/tables.html
and this
2. https://github.com/fletcher/MultiMarkdown-6
also check this
3. https://github.com/jeffreytse/jekyll-spaceship#rowspan-and-colspan

**Comment by tgrosinger** [comment]
@mafsi, I like the idea, but this plugin is only aiding the editing of tables, not how they are rendered. I'm not sure that plugins can even change how the markdown is rendered without creating a new view with a different rendering engine.

Unfortunately, this is outside the scope for this plugin.
