### ISSUE TITLE
use of YAML alias for a note inside table breaks things in live preview

### ISSUE THREAD

**Issue by koldex** [tgrosinger/advanced-tables-obsidian#200]
**Describe the bug**
Use of YAML alias for a note inside table breaks things in live preview. If you use alias to a note (which suffixes/separates a wikilink with | character to separate alias from the name) it does not render anymore correctly in live preview. 

**To Reproduce**
1. insert internal link inside table
2. use alias to refer to a note
3. view table in live preview

**Desktop (please complete the following information):**
 - OS: MacOS
 - Obsidian Version: 0.15.3
 - Advanced Tables Version: 0.17.3

**Comment by koldex** [comment]
workaround is to manually insert backslash (\) in from of | -character

**Comment by tgrosinger** [comment]
Yes, a backslash is the right course of action here. Thank you
