### ISSUE TITLE
Option to disable live preview 

### ISSUE THREAD

**Issue by Kanagram** [tgrosinger/advanced-tables-obsidian#201]
Hi Tony, 

I'm aware of the effort on getting live preview to render the table in an actual table format, but one of the things I loved about your plug-in was to be able to keep the text-based table style you have when you are editing the table, also when you leave the table (like it was working previously). Having an option to be able to disable it would be really nice.

So, when you are edditing the table, you have a format like:

![image](https://user-images.githubusercontent.com/95612595/179470300-6d5bf82d-36ac-4c60-b426-4b847bbed183.png)

When you leave it, it switches to:
![image](https://user-images.githubusercontent.com/95612595/179470377-fb99fd65-742a-4984-9555-c9590001d409.png)

What I'm asking for (if it is easy to do on your side) is to have a configuration option that defines if the preview should be changed to the live preview mode, or continue in the text mode. Basically, that for the tables to always be displayed like here, regardless if they have the focus or not:

![image](https://user-images.githubusercontent.com/95612595/179470716-ffebcb16-8913-444c-8902-ee253e565e72.png)

Regards, AG.

**Comment by tgrosinger** [comment]
Unfortunately this is not something I can control from the plugin. As far as I am aware the only way to do this would be to use the legacy editor.
