### ISSUE TITLE
LaTeX equations mess up live preview editor cell width

### ISSUE THREAD

**Issue by NerdKnight66** [tgrosinger/advanced-tables-obsidian#202]
**Describe the bug**
LaTeX equations mess up live preview editor cell width

**To Reproduce**
1. Make a table
2. Add inline LaTeX
3. Format the table
4. View in live preview
5. See error

**Expected behavior**
Table columns line up

**Desktop (please complete the following information):**
 - OS: Windows
 - Obsidian Version: v0.15.9
 - Advanced Tables Version: 0.17.3

**Comment by y9san9** [comment]
An example

<img width="836" alt="Снимок экрана 2022-12-18 в 17 42 24" src="https://user-images.githubusercontent.com/46930374/208304631-15b83bab-23ce-4d21-800a-9b9c234936fe.png">

**Comment by y9san9** [comment]
@tgrosinger it's such an annoying thing while doing math. Appreciate for your work, anyways this plugin is great!
