### ISSUE TITLE
Inconsistent rendering between edit mode and read mode

### ISSUE THREAD

**Issue by N0rdskog** [tgrosinger/advanced-tables-obsidian#205]
Advanced tables doesn't render the proper visual when Obsidian is set in "read mode", as opposed to edit mode. 

1. Make a table
2. Put text in the line over the table
3. Set Obsidian to "read mode"

**Expected behavior**
I expect the same visual as the one I automatically get in edit mode after I move the cursor away from the table. 

**Desktop (please complete the following information):**
 - OS: [OSX 10.13.6]
 - Obsidian Version: [v0.15.9]
 - Advanced Tables Version: [0.17.3]

**Comment by 888iee** [comment]
I have the same issue.
OS: [Win11 21H2 Build 22000.856]
Obsidian Version: [0.15.9]
Advanced Tables Version: [0.17.3]

**Comment by Altairys38** [comment]
Have the same issue 

- OS: [Win 10.0.17763 Build 17763
- Obsidian Version: [1.0.0]
- Advanced Tables Version: [0.17.3]

**Comment by hyukkyukang** [comment]
Have the same issue

OS: [OSX 13.0]
Obsidian Version: [1.0.0]
Advanced Tables Version: [0.17.3]

**Comment by cmcknight** [comment]
My workaround was to put in a single blank line before the table, but that's a workaround, not a fix.

**Comment by cestanis** [comment]
Same issue here and workaround does not work

**Comment by tgrosinger** [comment]
In markdown there should always be a blank line before tables. That should prevent this issue.
