### ISSUE TITLE
Plugin fails to load

### ISSUE THREAD

**Issue by khaled** [tgrosinger/advanced-tables-obsidian#207]
**Describe the bug**

I see the following in the developer tools console when trying to enable the plugin:

```
Plugin failure: table-editor-obsidian Error: ENOENT: no such file or directory, open '/Users/kagrama/Library/Mobile Documents/iCloud~md~obsidian/Documents/main/.obsidian/plugins/table-editor-obsidian/main.js'
```

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.4
 - Obsidian Version: v0.15.9
 - Advanced Tables Version: 0.17.3

**Additional context**
I took a peek in the `plugins/table-editor-obsidian` directory and noticed that indeed there is no `main.js`, just a `manifest.json` and a `styles.css`

**Comment by khaled** [comment]
I uninstalled and re-installed and things started working  🤷🏽‍♂️

**Comment by junzhounbu** [comment]
Yes, I uninstalled, it because no  main.js
