### ISSUE TITLE
Advanced Table takes up a lot of empty space in live preview mode

### ISSUE THREAD

**Issue by jerrysoft-x** [tgrosinger/advanced-tables-obsidian#208]
I noticed that advanced table takes up a lot of empty space in live preview mode, but this is not a problem in reading view. It’s a little bit uncomfortable.
My obsidian version is 0.15.9, and the version of advanced table is 0.17.3

See the screenshots below:
https://forum.obsidian.md/uploads/default/original/3X/c/3/c37e9790c027ae823566bda23aebeed8148bdcff.png
https://forum.obsidian.md/uploads/default/original/3X/7/8/780ab3fa4f9dd60ec343ec7d9d792deef1db1f9d.png

Desktop (please complete the following information):

OS: [Microsoft Windows 10 Enterprise 10.0.19044 Build 19044]
Obsidian Version: [v0.15.9]
Advanced Tables Version: [0.17.3]

**Comment by Comprehensive-Jason** [comment]
I think that's an issue with your theme, not Advanced Tables. Are you having the same issue using the default theme?

**Comment by tgrosinger** [comment]
This plugin does not affect how tables are rendered in preview mode or reading mode. It only affects editing tables. Please look into this issue with the creator of the theme you are using.
