### ISSUE TITLE
When table overflows out of the visible area, insert row and delete row take two clicks

### ISSUE THREAD

**Issue by greenmanspirit** [tgrosinger/advanced-tables-obsidian#21]
**Describe the bug**
When table overflows out of the visible area, insert row and delete row take two clicks. The first click moves the cursor to the end of the row and the second click performs the action.

**To Reproduce**
1. Create table with width greater than the visible area
2. Try to insert or delete row

**Expected behavior**
The row to be inserted or deleted

**Screenshots**
![advanced-tables-issue](https://user-images.githubusercontent.com/31684/98430468-820eb400-207b-11eb-910e-f217613a45d1.gif)

**Desktop (please complete the following information):**
 - OS: elementary OS
 - Obsidian Version: 0.9.10
 - Advanced Tables Version: 0.5.3

**Comment by tgrosinger** [comment]
Ah, yeah I have seen this before too. I'm not 100% sure what is happening here. The toolbar is a CodeMirror line widget which I configure to `handleMouseEvents: true`. I am not sure why clicking in it triggers scrolling the viewport.

Let me see if Licat or Silver can shed some light.
