### ISSUE TITLE
Cell fusion

### ISSUE THREAD

**Issue by Chrstn67** [tgrosinger/advanced-tables-obsidian#211]
Hello,

Sorry, i'm french and my english is very poor, so je fais de mon mieux...

I've an idea to upgrade your plugins...
Is it possible to fusion cell like Excel, please ?
Or maybe that i did not understand where is this option ;D

Thanks for your reading.

Bye.
C

**Comment by tgrosinger** [comment]
Hello,
If I understand correctly you are asking if two cells can be merged and displayed as a single wider cell?

Unfortunately that is not possible within Obsidian. It's a limitation of the Markdown variety they are using. Please work with the Obsidian developers if you would like them to add support for extended table syntax that would enable features like that.
