### ISSUE TITLE
Multiple lines of text in a cell

### ISSUE THREAD

**Issue by mrickey** [tgrosinger/advanced-tables-obsidian#215]
**Is your feature request related to a problem? Please describe.**
I have a task list I would like to fit on a single page. In Docs, I would simply create a table and put part of the list in either column. Easy. If I include a line break in a cell Advanced Tables gets confused.

**Describe the solution you'd like**
I would very much like the ability to have a mix of paragraph text and task list items in a single cell.

**Describe alternatives you've considered**
I haven't really found any, not sure what else to try. Suggestions?

**Comment by tgrosinger** [comment]
This plugin is not able to add support for multiple lines within a table cell. That is a feature of the markdown syntax itself, not just the formatting and rendering. Sorry.

**Comment by JESii** [comment]
Actually, this is easy to do, considering that the markdown spec includes the ability to use whatever HTML tags you want. Here's what I do:
```
| ticket | Description/Comments |
|  4868  | Create Postman test suite <br/>\* Some work may already have been done?<br/>\* Check this out |
```
<img width="561" alt="CleanShot 2022-12-08 at 12 43 46@2x" src="https://user-images.githubusercontent.com/486/206563706-21c70771-7912-463d-b9ef-ee90821a6c85.png">
