### ISSUE TITLE
More of a Question

### ISSUE THREAD

**Issue by mischiefpoet** [tgrosinger/advanced-tables-obsidian#217]
Hello, 

How would I go about merging rows together in a single advanced table? 

Please see screenshot below: 
<img width="631" alt="image" src="https://user-images.githubusercontent.com/92902931/197601043-3faf8fe4-8a8d-4965-b61e-b5ca8995ddae.png">
or this code: 
| Statistical symbols |                    |              |
| ------------------- | ------------------ | ------------ |
| symbol              | name               | code         |
| ------------------- | ------------------ | ------------ |
|                     |                    |              |
| $\bar{x}$           | mean               | `$\bar{x}$`  |
| $\mu$               | population mean    | `$\mu$`      |
| $\sigma$            | standard deviation | `$\sigma$`   |
| $\sigma^2$          | variance           | `$\sigma^2$` |

I want my top row "Statistical Symbols to be in a single long row cell, centered. How do I go about this without breaking the table? 
This below doesn't seem to work. 

| Statistical symbols | 
| ------------------- | ------------------ | ------------ |
| symbol              | name               | code         |
| ------------------- | ------------------ | ------------ |
|                     |                    |              |
| $\bar{x}$           | mean               | `$\bar{x}$`  |
| $\mu$               | population mean    | `$\mu$`      |
| $\sigma$            | standard deviation | `$\sigma$`   |
| $\sigma^2$          | variance           | `$\sigma^2$` |

Thank you :)

**Comment by tgrosinger** [comment]
I'm going to close this issue due to inactivity. Please feel free to reopen if you add more details.
