### ISSUE TITLE
Monospace

### ISSUE THREAD

**Issue by testgoofy** [tgrosinger/advanced-tables-obsidian#22]
**Describe the solution you'd like**
If a table is created, a monospace font should automaticly be selected

**Comment by tgrosinger** [comment]
Oh, that's an interesting idea. I think I can make that happen. Let me take a stab at it.

**Comment by tgrosinger** [comment]
Done in 8f9d53a5b03cc805233e5598812d621328fb63fa

**Comment by DutchPete** [comment]
Tony, does that mean that when one makes a table monospace is only used for that table?
In other words, could I go back to having a non-monospace font in Edit mode, and still make full use of your fantastic plug-in and have it perform as designed?

**Comment by tgrosinger** [comment]
Yes, that is exactly right. It will automatically use a monospace font in just the table area.
Best of both worlds 😃

**Comment by DutchPete** [comment]
I have changed my default font back to non-monospaced, and enabled monospace in the settings.
I can report that it works!! Many thanks.
