### ISSUE TITLE
Failed to enable plugin in 1.0

### ISSUE THREAD

**Issue by StevenGann** [tgrosinger/advanced-tables-obsidian#222]
**Describe the bug**
On startup Obsidian does not enable this plugin. Manually enabling on the list of installed plugins fails and shows a "Failed to enable plugin" toast. Going into the community Plugin list and pressing the enable button there causes the same error, but the plugin enables and functions correctly despite the error.

**To Reproduce**
1. Install the latest Obsidian (1.0.3) on Windows or Linux
2. Install the latest version of this plugin
3. Attempt to enable the plugin
4. See error in console

```
app.js:1 Plugin failure: table-editor-obsidian DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at r4.<anonymous> (app://obsidian.md/app.js:1:1032505)
    at app://obsidian.md/app.js:1:235201
    at Object.next (app://obsidian.md/app.js:1:235306)
    at a (app://obsidian.md/app.js:1:234045)
```

**Expected behavior**
I expect the plugin to be enabled on startup.

**Desktop (please complete the following information):**
 - OS: Windows and Linux.
 - Obsidian Version: 1.0.3
 - Advanced Tables Version: 0.17.3

**Comment by rechengehirn** [comment]
@StevenGann had the same error. After Updating the Advanced Tables Plugin everything works.

**Comment by zhuzhzh** [comment]
I encounter the same error. I can't enable any community plugin now.

**Comment by tgrosinger** [comment]
Please make sure you have updated Obsidian and the plugin. If it is still not working please delete the plugin and install again.
