### ISSUE TITLE
Table control bar doesn't work!!

### ISSUE THREAD

**Issue by Issam-seghir** [tgrosinger/advanced-tables-obsidian#233]
**Describe the bug**
The table control bar doesn't work!! when using Shortcut or control panel!!

**Thing I Have tried** 
 - click `ctrl + shift + d` when curser focus on the table 
 -  ` Open command panel > Advanced Tables: Open table controls toolbar`

**Expected behavior**
Show the control bar 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows Version 21H2 (OS Build 190442075)

 - Obsidian Version: 1.1.8
 - Advanced Tables Version: 0.18.1

![](https://i.imgur.com/AUvvfCR.gif)

**Comment by tgrosinger** [comment]
Hello,
The table control panel has been moved to the right sidebar. Thanks

![Screenshot 2023-05-25 080834](https://github.com/tgrosinger/advanced-tables-obsidian/assets/597386/dce2c5b4-5041-4b19-8bec-c5be774198cb)
