### ISSUE TITLE
Inconsistent behavior on Kubuntu 22.04

### ISSUE THREAD

**Issue by OnkelTem** [tgrosinger/advanced-tables-obsidian#234]
**Describe the bug**
I enabled the plugin, but it works once in a while

**To Reproduce**
1. Install and enable
2. Go to a note, type `| text <Tab>`
3. It may work or may not work

**Expected behavior**
Work as expected

**Screencasts**
https://youtu.be/yye1Bc5q1hg

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04
- SYSTEM INFO:
	Obsidian version: v0.15.9
	Installer version: v0.15.9
	Operating system: Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 5.15.0-56-generic
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Advanced Tables v0.17.0

**Comment by tgrosinger** [comment]
I'm going to merge this issue with #256
