### ISSUE TITLE
Bolded text distorts alignment while editing

### ISSUE THREAD

**Issue by SanderDeVeth** [tgrosinger/advanced-tables-obsidian#236]
**Describe the bug**
While editing a table with bolded text the columns are offset from their correct position.
Selecting the bolded text makes the asterisks visible again and negates the problem.

**To Reproduce**
1. Make a new Advanced Table with two or more rows
2. Bold the text of any word or row
3. Click on empty cell or unmarked text
4. See error (misaligned columns)

**Expected behavior**
While editing a table, I would like the asterisks (or other markdown characters) to be compensated for by extra spaces at the end of the cell when the characters are not shown in order to keep the layout of the table the same whether words are selected or not.

**Screenshots**
[Comparison screenshot](https://i.imgur.com/76vM7iy.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version: 1.1.9
 - Advanced Tables Version: 0.17.3

**Comment by PointedOne** [comment]
I'm getting the same results. If some field with bold text (let's name it fieldX) have more text than any other field in the same row, then all those fields in row will stretch to match fieldX width - treating **** as normal letters. At the same time, fieldX won't treat **** as normal letters and the result is that the width of fieldX is shorter than rest of fields in the same row by 4 letters.

**Comment by MiguelGuthridge** [comment]
This also happens with `code` segments written using \` backticks, seems like it ignores hidden characters in the width calculation

**Comment by tgrosinger** [comment]
Please see #145.
