### ISSUE TITLE
A way to set column width or row height

### ISSUE THREAD

**Issue by DumbledoreCalrissian** [tgrosinger/advanced-tables-obsidian#238]
**Is your feature request related to a problem? Please describe.**
I don't think so. Currently, rows and columns auto-resize. I'd like to change that.

**Describe the solution you'd like**
A way to set column width and row height. (similar to how it might work in LaTeX maybe?)

**Describe alternatives you've considered**
Right now, I don't know an alternative that does this for me.
(Is there way to do it in html?)

**Comment by architchandra** [comment]
I'd also like an option to control the column width.

Use-case: I have to create a table where one column contains durations eg. `0500 - 0630`. The table wraps such that the end time comes in the second line. I'd like the duration to be in one line.

Currently, I'm working around this by using the non-breaking space HTML entity (`&nbsp;`), like so: `0500&nbsp;-&nbsp;0630`. But this is far from elegant and I would appreciate a better solution.

PS - Thank you so much for creating this plugin. It makes life so much easier. :)

**Comment by tgrosinger** [comment]
Thanks for the suggestion. Unfortunately this plugin is not able to affect how the tables are displayed when rendered. For that, using things like `&nbsp;` and `<br/>` are going to be the best options that I am aware of. You might also try discussion this in the Obsidian forum or Discord to see if anyone has other ideas there. https://obsidian.md/community

**Comment by architchandra** [comment]
Thanks for replying, @tgrosinger. I'll see if I can find some other workaround or make my case in the community. Very helpful plugin overall. :)
