### ISSUE TITLE
Not recognizing simple tables

### ISSUE THREAD

**Issue by NomarCub** [tgrosinger/advanced-tables-obsidian#24]
I have a table with the following structure

```
a | b | c
-|-|-
d | e | f
```

It renders fine on Obsidian (and Github)

a | b | c
-|-|-
d | e | f

But when I click the plugin button it says `Cursor must be in a table`, with the cursor in the table or even in a cell, both in edit and preview mode.

I use Windows 10, Obsidian v0.9.10, Advanced Tables 0.5.5

**Comment by tgrosinger** [comment]
Hi @NomarCub,
This plugin requires tables have a pipes on the outside of the table and a heading divider. So for example, instead of 

```
a | b | c
-|-|-
d | e | f
```

you would write

```
| a | b | c |
| -|-|- |
| d | e | f |
```

Adding support for the table format you mentioned is tracked by #9.
