### ISSUE TITLE
break line element offsets y-axis especially in scrollable files

### ISSUE THREAD

**Issue by VictorJermiin** [tgrosinger/advanced-tables-obsidian#241]
**Describe the bug**
I was making a table for an exam and eventually it became really big with lots of rows. I wanted to write several lines in one row so I used \<br\> break line.
So it appears that for large scrollable documents with \<br\> it becomes a nightmare going from source code view to reading view because the y-axis is offset making it hard to find what you just wrote in edit mode.

**To Reproduce**
1. make a very large table with lots of rows and lots of \<br\> so that you have to scroll to see the whole document. (the more rows and \<br\>, the more obvious the bug becomes)
2. try switching from reading view to source code view ex. when you have scrolled to the middle of the document

**Expected behavior**
The break line element should be accounted for so that I don't get teleported to another part of the table and have to find where I just wrote stuff.

**Desktop:**
 - OS: Windows 10
 - Obsidian Version: v1.1.9
 - Advanced Tables Version: 0.18.1

(note that when neither reading nor source code view in enabled there is another bug where \<br\> messes with the table, but it not that big of a problem for me and it is not the problem I'm describing here)

**Comment by tgrosinger** [comment]
Thanks for the suggestion. This plugin is only changing how tables are edited, not how they are displayed in preview mode. It also can't add new syntax or features to markdown tables. Unfortunately this request is not something this plugin can add.
