### ISSUE TITLE
Panel & tooltip hidden

### ISSUE THREAD

**Issue by ckdarby** [tgrosinger/advanced-tables-obsidian#243]
**Describe the bug**
Installing Advance table after a fresh install of Obsidian causes the plugin to not show up in the panel on the right side nor does the tooltip work when select a row in a table.

**To Reproduce**
1. Install Obsidian (obsidian_1.1.9_amd64.deb)
2. Install Advance Tables via community plugins
3. Make a new table
4. Select table
5. ctrl+shift+d (using the hotkey for the panel) then magically allows the panel to show up *and* the clickable icon for advance tables to appear

**Expected behavior**
1. Right panel for advance table shows up
2. Selecting a row within a table allows for the tooltip to come up

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS
 - Obsidian Version: v1.1.9
 - Advanced Tables Version: currently installed 0.18.1

**Additional context**
I noticed in Obsidian that sometimes the panel gets cut off in the bar section, but the tooltip never works when selecting a row in a table.

**Comment by tgrosinger** [comment]
To make the panel show up, please click the table icon in the left sidebar ribbon.
