### ISSUE TITLE
the plugin don't work in a long passage。

### ISSUE THREAD

**Issue by morning-start** [tgrosinger/advanced-tables-obsidian#244]
in the normal passage, the plugin failure

![有内容](https://user-images.githubusercontent.com/76601464/217492227-5bc38f0c-1187-4dc0-9e13-6c2aa2f1a36f.gif)

but in empty passage, plugin works

![无内容](https://user-images.githubusercontent.com/76601464/217492204-18a77b44-3943-4689-9ca7-195ed9fc266c.gif)

**Comment by jeremydescamps** [comment]
Hi @morning-start , I have the same behavior you have in your first image.
But I am not able to do what you did in the second image.
But I don't see any difference between both images, except the first one does not work and the second one doesn't.

For me the plugin does not work using Obsidian v1.1.15

**Comment by tgrosinger** [comment]
I'm going to close this issue due to inactivity. Please reopen if you can add more details. Thank you.
