### ISSUE TITLE
Columns with boolean type 

### ISSUE THREAD

**Issue by SalamanderXing** [tgrosinger/advanced-tables-obsidian#246]
**Is your feature request related to a problem? Please describe.**
I was trying to insert a checkbox inside the column, but I saw that's not possible.

**Describe the solution you'd like**
Mark a column as a boolean. Each cell in that column is then represented as a checkbox (defaulted to false, unchecked)

**Describe alternatives you've considered**
Allowing insertion of checkboxes into table cells. 

**Additional context**
coda.io I know works like I suggested but probably many other similar tools

**Comment by SalamanderXing** [comment]
Thank you. I'd be happy to contribute to that feature btw.

**Comment by pterodactyl-soup** [comment]
> As a workaround, you can insert a checkbox using HTML: `<input type="checkbox"/>`. Or `<input type="checkbox" checked />` for one that's checked. Just paste that into the table cell and it will give you a checkbox.
> 
> But I agree, would be better if we could do it with markdown instead.

Can we use that value of check mark in a spreadsheet formula? Ex. 4 of 5 tasks for project 1 finished. Project 1 has associated formula 80% inputted into a Percent box. I'm not sure of other better ways of doing this, I'm used to it with Notion.

**Comment by tgrosinger** [comment]
Thanks for the suggestion. This plugin is only changing how tables are edited, now how they are displayed in preview mode. It also can't add new syntax or features to markdown tables. Unfortunately this request is not something this plugin can add.
