### ISSUE TITLE
Compatible with resizing embeded image

### ISSUE THREAD

**Issue by Qinggao1729** [tgrosinger/advanced-tables-obsidian#247]
**Is your feature request related to a problem? Please describe.**
I want to embed an image and adjust its size in the table, but when I do this, it doesn't behave well, because the vertical string that should be used to indicate the size is used as a separator of cells.

**When editing the cell, which works fine:**
![image](https://user-images.githubusercontent.com/80807549/219849541-0b4c82c5-6ea5-4bf1-ab1d-1c167a198926.png)

**When moving the cursor to another place (end editing the cell, both in reading mode and editing mode), which works not as expected:**
![image](https://user-images.githubusercontent.com/80807549/219849558-9e729d8f-beab-40ae-90b0-a3a3c0381827.png)

**Describe the solution you'd like**
Check if the separator is inside of a double square bracket.

**Comment by Qinggao1729** [comment]
And inserting images doesn't work well in reading mode either.

Editing view:
![image](https://user-images.githubusercontent.com/80807549/220223812-9de399e0-09ea-4632-a224-b7318a491939.png)
Reading view:
![image](https://user-images.githubusercontent.com/80807549/220223916-a8f01980-37b6-4712-a1ea-1d89e0d86f22.png)
Source mode:
```
|property| injection                                  | not injection                              |
| --- | ------------------------------------------ | ------------------------------------------ |
| surjection    | ![[Files/Pasted image 20230217235636.png]]| ![[Files/Pasted image 20230217235443.png]] |
|  not surjection |    ![[Files/Pasted image 20230217235339.png]]     | ![[Files/Pasted image 20230217235659.png]] |
```

**Comment by tgrosinger** [comment]
This plugin only considers the text of the image link itself (`![[Files/Pasted image 20230217235636.png]]`). It doesn't know about the actual contents of the image. It also doesn't have any affect on how tables are previewed.

For the divider issue, please use a backslash before the pipe character. For example `![[Files/Pasted image 20230217235636.png\|100]]` See #31 for more details.
