### ISSUE TITLE
Editing an svg file replaces the Files tab

### ISSUE THREAD

**Issue by tomvecchi** [tgrosinger/advanced-tables-obsidian#248]
**Describe the bug**
When the "Edit diagram" option is selected on an svg file in the Files tab, the editor opens in the window currently occupied by the Files tab. When this occurs, it replaces the Files tab, making it impossible to view the file tree again without resetting or re-opening Obsidian. While this is not a particularly serious bug, it is a bit annoying to lose Files often while editing multiple documents.

**To Reproduce**
1. Have one or more SVG files in the current vault
2. Right-click on any SVG file and select "Edit diagram"
3. The editor will take up the onscreen space previously occupied by the Files tab
4. Close the editor tab
5. The Files tab's icon is now gone from the top bar. 

**Expected behavior**
Preferably, the editor should be opened in a new tab when invoked from the Files tab. Then, when the editor is closed, the Files tab is still available. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS
 - Obsidian Version: 1.1.9
 - Advanced Tables Version: 0.18.1

**Comment by tgrosinger** [comment]
This doesn't sound like it's related to the Advanced tables plugin. Please report this issue to the Obsidian developers.
