### ISSUE TITLE
Table Caption

### ISSUE THREAD

**Issue by NilsHempel** [tgrosinger/advanced-tables-obsidian#25]
**Is your feature request related to a problem? Please describe.**
Much like in academic papers a table sometimes should have a caption to identify it more clearly.

**Describe the solution you'd like**
Create the `<caption>This is a caption</caption>` automatically

**Describe alternatives you've considered**
Another way is using a text expander; this is what I'm currently doing:
```
||||
|---|---|---|---|---|
|||||
|||||
|||||
|||<caption>This is a caption</caption>|  
```

**Comment by tgrosinger** [comment]
Hi @NilsHempel,
I'm not quite following what the desired outcome is. Are you looking for the last row to have a caption tag added as shown in your example? I'm not familiar with another method of adding captions to tables in markdown.

**Comment by NilsHempel** [comment]
Yes, sorry for not being more clear (and thank you for this plugin!): I think many people don't know about caption tags and would like a functionality like this. Adding this tag at the click of a button around selected text might be a way to do this. 

I have come to add the caption to my tables as a good practice so I can export the documents better to other formats as well and have properly formatted tables.

**Comment by tgrosinger** [comment]
It sounds like the caption tag is just an HTML tag that is not actually directly related to tables. I think this feature sounds interesting, but it would be better added to a different plugin. 

Maybe something like the Hotkeys++ plugin?
