### ISSUE TITLE
Excellent form transformation

### ISSUE THREAD

**Issue by MyAnivia** [tgrosinger/advanced-tables-obsidian#254]
**There are three common-sight table forms, it's so excellent if you can transform them freely**
![230329011724-1367x1140](https://user-images.githubusercontent.com/120353247/228318027-0140e486-ed99-4302-a2df-2270f5d99c37.jpg)

**Comment by tgrosinger** [comment]
Hello, this is not a feature I will be able to add to this plugin. Thank you for the suggestion.
