### ISSUE TITLE
PDF export makes header invisible

### ISSUE THREAD

**Issue by WikGru** [tgrosinger/advanced-tables-obsidian#257]
On exporting to PDF table header has a color close to white which leads to worse readability

1. Create a table
2. Export document to PDF
3. Observe almost invisible header font

![Example](https://user-images.githubusercontent.com/25268011/233060724-81944ad0-4364-439e-9a35-4e79c79dc5a4.png)

**Comment by bhuveh** [comment]
Same, thanks.

**Comment by tgrosinger** [comment]
This plugin does not affect the pdf export. Please work with the Obsidian developers on this issue.
