### ISSUE TITLE
Copy Cell contents to cell below

### ISSUE THREAD

**Issue by half-adder** [tgrosinger/advanced-tables-obsidian#258]
**Is your feature request related to a problem? Please describe.**

I'm often filling out a table with the same value in multiple cells in a column. Copy/Pasting works ok, but the formatting gets weird when you paste until you hit tab, and it could be faster.

**Describe the solution you'd like**

It would be nice to have a command that copies the contents of the current cell and pastes it into the cell below, and then moves the cursor to that cell (so that you could e.g. repeatedly hit the same shortcut and fill out a whole column).

**Describe alternatives you've considered**

**Additional context**

**Comment by tgrosinger** [comment]
Thanks for the suggestion. I understand your request, but I want to be careful to not add so many commands that the plugin becomes too complicated to use.

I think for now sticking with copy/paste and the pressing tab is the best option. You could also bind a hot key to one of the table format commands.

![Screenshot 2023-05-25 082800](https://github.com/tgrosinger/advanced-tables-obsidian/assets/597386/2ba52444-7678-4c86-a451-32a323b0c46a)
