### ISSUE TITLE
Add option to ignore Markdown and HTML syntax when padding the cells.

### ISSUE THREAD

**Issue by zycsss** [tgrosinger/advanced-tables-obsidian#259]
Now the Padding feature also takes Markdown and HTML syntaxes as text. For example, `*sometext*` or `<mark style="background: #FF5582A6;">sometext</mark>`

I wish that I can have an option to let the plugin only consider "sometext" as text, but not the `**` and the `<mark style="background: #FF5582A6;"></mark>`, so the table won't be a mess when I want to highlight something or border text.

**Comment by tgrosinger** [comment]
Please see #145 which discusses this about Markdown. I believe the same response applies to HTML.
