### ISSUE TITLE
Turn the table into Kanban view 

### ISSUE THREAD

**Issue by trongnguyen29** [tgrosinger/advanced-tables-obsidian#26]
Is it feasible to turn the table into a Kanban view, or different board view like notion, either through Mermaid or through converting into an image?

Or maybe just turn a table into a different table using a specific column entries as column headings?  So there will be the original table and a transformed "view"/table?

**Comment by tgrosinger** [comment]
Hi @trongnguyen29,
That's an interesting idea, and sounds useful, but I think it is outside the scope of this plugin. With this plugin I am focusing on table editing, and not how tables are displayed.

You could suggest the idea in the `Plugin Ideas` section of the forum, or the Plugins channel in Discord though to see if anyone wants to pick it up.
