### ISSUE TITLE
Tables displays incorrectly (sideways scrollbar)

### ISSUE THREAD

**Issue by Hailst0rm1** [tgrosinger/advanced-tables-obsidian#264]
**Describe the bug**
With (probably the most recent obsidian update) my tables have gotten a sideways scrollbar.

**To Reproduce**
1. Create a table
2. All plugin settings turned on

**Expected behavior**
A table that utilize the width without requiring a scrollbar.

**Screenshots**
![Screenshot_1](https://github.com/tgrosinger/advanced-tables-obsidian/assets/60173507/7323a63e-d7a2-499a-8da2-d8dae052be5b)

**Desktop (please complete the following information):**
 - OS: Windows
 - Obsidian Version: 1.3.4
 - Advanced Tables Version: 0.18.1

**Comment by tgrosinger** [comment]
Hello,
This plugin does not affect how plugins are rendered in Obsidian. It only affects the editing experience. Please discuss this issue with the Obsidian developers.
