### ISSUE TITLE
Cannot create a checkbox inside a cell using [ ]

### ISSUE THREAD

**Issue by gyurisc** [tgrosinger/advanced-tables-obsidian#265]
**Is your feature request related to a problem? Please describe.**
Cannot create a checkbox inside a cell using [ ]

**Describe the solution you'd like**
I would like the [ ] to become a checkbox in the read only mode that can be checked and unchecked

**Describe alternatives you've considered**
I am just observing your great plugin and did not observed other solutions; 

**Additional context**
Maybe this is an obsidian problem and not a problem with your plugin

**Comment by tgrosinger** [comment]
This appears to be a duplicate of #99 and #246. Please see those issues.
