### ISSUE TITLE
A bug occurs after rendering the embedded templater statement in the table

### ISSUE THREAD

**Issue by bsszds** [tgrosinger/advanced-tables-obsidian#268]
**Describe the bug**
A bug occurs after rendering the embedded templater statement in the table

**To Reproduce**
1. The table under the source code is displayed normally
2. When applying a template to generate notes, after getting the result, the rendering display appears that the terms do not match

**Expected behavior**
Entries correspond one-to-one

**Screenshots**
1, What it looks like before rendering
![image](https://github.com/tgrosinger/advanced-tables-obsidian/assets/52306372/8e7c418c-532b-4eb4-a440-4a994b48161e)
2，What it looks like after rendering
![image](https://github.com/tgrosinger/advanced-tables-obsidian/assets/52306372/5aab410f-c8df-4b10-9d31-5a8289efdf60)
3，Option settings for the templater plugin
![image](https://github.com/tgrosinger/advanced-tables-obsidian/assets/52306372/bd748a53-aee5-47a4-bd6c-30f557b2206d)
4，The original templates statement
![image](https://github.com/tgrosinger/advanced-tables-obsidian/assets/52306372/91b372d1-b489-4a0b-a4d3-6e1bcbb381e3)
![image](https://github.com/tgrosinger/advanced-tables-obsidian/assets/52306372/04768db1-7340-48ca-a6b6-27809bf8bf32)

**Desktop (please complete the following information):**
 - OS: windows 11.0
 - Obsidian Version: v1.3.5
 - Advanced Tables Version: 0.18.1

**Additional context**
……

**Comment by tgrosinger** [comment]
Hello,
Thank you for filing an issue. It sounds like you are having trouble with how the content is displayed when rendered. Unfortunately that is not something which this plugin is able to alter. This plugin only makes it a little easier to edit the tables in markdown by adding keyboard shortcuts and whitespace.

It might be helpful to post this question in the Obsidian forum or Discord to ask if they can help with why your table is not displaying properly. https://obsidian.md/community
