### ISSUE TITLE
Subheadings?

### ISSUE THREAD

**Issue by davidfsnyder** [tgrosinger/advanced-tables-obsidian#270]
I'd like to make a table with first column headed by chore/topic/task and then seven day name columns that have subheadings (say 4) for certain times in the day. This is to be used as a check list (check array, really).

For now, as a workaround, I create a separate column for each individual time, but then I'm repeating information (the day symbol) so it's not as efficient as I would like.

**Comment by tgrosinger** [comment]
Hello,
This plugin is not able to change what markdown is allowed or how tables are structured. It only affects how you edit tables. If I understand your request, it sounds like you're asking for new features in markdown table syntax, which is unfortunately not something this plugin can provide.

**Comment by davidfsnyder** [comment]
Thank you for the clarification.
