### ISSUE TITLE
Need ability to center text in a table cell and maintain consistent editing display

### ISSUE THREAD

**Issue by JESii** [tgrosinger/advanced-tables-obsidian#271]
**Describe the bug**
I want to create a cell in the table and have the text centered in that cell. When I do that using the `<center>...</center>` tag, it works, but the editing display goes all hinky.

**To Reproduce**
1. Create a table with a three column and enter some text data
2. In one of the rows in column 2, center the text using `<center>...</center>` tags
3. Move down off that row and notice what happens to the display... the text which used to fit on line now spans multiple lines

**Expected behavior**
I would  have expected the display to remain on a single line -- when I use other tags, such as `<br/>` tags, the display isn't hosed.

**Screenshots**
**displays as expected when not "in" the table (cursor is on line 2**
<img width="773" alt="CleanShot 2023-07-07 at 11 13 50@2x" src="https://github.com/tgrosinger/advanced-tables-obsidian/assets/486/6d0a70a2-d1d6-4fa5-bee7-c1a888adc227">
**click "edit this block" and things still look good**
<img width="745" alt="CleanShot 2023-07-07 at 11 14 53@2x" src="https://github.com/tgrosinger/advanced-tables-obsidian/assets/486/4224141e-66ab-44c2-948c-a7a65e19d540">
**click into the table and things still look good**
<img width="1123" alt="CleanShot 2023-07-07 at 11 16 01@2x" src="https://github.com/tgrosinger/advanced-tables-obsidian/assets/486/dff16a44-2aa8-4087-ae94-18917c547eee">
**but as soon as I click on a cell to do some edits... goes a bit haywire**
<img width="1111" alt="CleanShot 2023-07-07 at 11 16 36@2x" src="https://github.com/tgrosinger/advanced-tables-obsidian/assets/486/ffde6f6d-e02b-44c8-8b93-0d00aab3920a">
**If I'm actually on one of those 'centered' items, it looks OK, but others do not**
![CleanShot 2023-07-07 at 11 01 45@2x](https://github.com/tgrosinger/advanced-tables-obsidian/assets/486/514f021e-8959-4619-9e32-17ecdd2e8e62)

**Desktop (please complete the following information):**
 - OS: Ventura 13.4.1 (22F82)
 - Obsidian Version: v1.3.7
 - Advanced Tables Version: v1.18.1
 - 
**Additional context**

It's workable, but very disconcerting.

**Comment by tgrosinger** [comment]
This appears to be working as expected. There are formatting tags (`</br>` for example) and empty whitespace which are being hidden when your cursor is not in the table, but displayed as soon as you click into it.

If you were to view this file in a program other than Obsidian, you could see how the whitespace makes the table appear nicely formatted when viewed as plain text.

For more details on this please see #145.
