### ISSUE TITLE
tags on the line immediately above the table cause the table not to render

### ISSUE THREAD

**Issue by randomlogic78** [tgrosinger/advanced-tables-obsidian#274]
**Describe the bug**
Line with tags immediately preceding the table cause the table not to render. 

**To Reproduce**
1. Create a new note
2. create a tag on the first line
3. On the next line, create a table, any number of columns, any number of rows
4. exit the table

i.e.
#foo/bar
| foo | bar | foobar |
| --- | --- | ------ |
| some | data | or info |

5. The table will not render in preview or edit mode
6. Using the command pallet command to render all tables also fails to render the table

**Expected behavior**
Table should render

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS, Ventura, 13.4.1 (22F82)
 - Obsidian Version: Version 1.3.5 (Installer 1.1.16)
 - Advanced Tables Version: 0.18.1

**Additional context**
Incidentally, any content other than a blank line above the table causes the table not to render. However, only the tags are important for me. If blank lines are required for a markdown standard, consider this a feature request to add an exception to allow for tagging tables on the proceeding line in the plugin settings.

**Comment by tgrosinger** [comment]
Please see the discussion in #262 about this issue. Unfortunately this is not something within the control of this plugin. It's an effect of how Obsidian is rendering the markdown.
