### ISSUE TITLE
Autoformat minus into bullet points

### ISSUE THREAD

**Issue by CouscousPie** [tgrosinger/advanced-tables-obsidian#278]
I think of bullet lists in tables as a highly valuable thing to offer as tables are a beneficial format for gaining oversight over and structuring plenty of information. Most of the time, it makes sense to structure tables in a way that doesn't restrict a single piece of information to a single cell and instead categorizes rows and columns in such a way, that multiple pieces of information belong into one cell. At the moment, it seems like this feature is missing in vanilla obsidian as well as in this plugin. Adding `</br>` to the end of every single bullet point as a workaround is inconvenient and feels redundant.

I suggest to automatically format a minus into a bullet point if it is detected at the beginning of a cell and additionally followed by a space. Continue to format minuses into bullet points if a word is followed by a space a minus and a space.

Alternatively, a bullet list could be indicated via shortcut like CTRL+- or Shift+Enter then brings you to the next entry of the list.

**Comment by baujathan** [comment]
Interested to see this functionality as well.  In my workflow I use tables with bullets frequently and this is cumbersome in markdown table formats.  Something to enhance the ability to do this would be great.

**Comment by tgrosinger** [comment]
Markdown doesn't allow multiple lines or lists in tables, however please see #215 for a workaround.
