### ISSUE TITLE
Spreadsheet formula concatenation

### ISSUE THREAD

**Issue by Elec0** [tgrosinger/advanced-tables-obsidian#280]
I want to be able to concatenate text into a cell after a formula has been evaluated, like so:

| Movespeed (ft/6s) | Distance Per Minute (ft) | Distance Per Hour (mph)
| ----------------- | ------------------------ | -----------------------
| 195               | 1950                     | 22.15902               
| 165               | 1650                     | 18.74994               

`<!-- TBLFM: $3=($2*0.0113636) & " mph" -->`
(I'm using the Google Sheets equivalent '&' concat operator)

Which would display:
| Movespeed (ft/6s) | Distance Per Minute (ft) | Distance Per Hour (mph)
| ----------------- | ------------------------ | -----------------------
| 195               | 1950                     | 22.15902 mph               
| 165               | 1650                     | 18.74994 mph               

Is that possible?

**Comment by tgrosinger** [comment]
Hello, I agree that this would be a great feature to add. It's currently being tracked here: https://github.com/tgrosinger/md-advanced-tables/issues/35
