### ISSUE TITLE
Table formatting wrong when code snippets or latex in cells

### ISSUE THREAD

**Issue by jannismain** [tgrosinger/advanced-tables-obsidian#281]
**Describe the bug**
The table formatting is wrong when cells contain code snippets or latex.

**To Reproduce**
1. Create a table
2. Add \`foo\` in table cell
3. Autoformat table

**Expected behavior**
Vertical lines should match those in heading

**Screenshots**
![CleanShot 2023-08-08 at 08 24 36](https://github.com/tgrosinger/advanced-tables-obsidian/assets/14290527/5bc244d4-8d80-49d4-95bd-c513bdc2572b)

![CleanShot 2023-08-08 at 08 28 01](https://github.com/tgrosinger/advanced-tables-obsidian/assets/14290527/d6320613-c13e-40b6-9872-d11a2cb82b0d)

**Desktop (please complete the following information):**
 - OS: macOS
 - Obsidian Version: 1.3.7
 - Advanced Tables Version: 0.18.1

**Comment by tgrosinger** [comment]
Hello, thank you for the issue report. This is the same issue as #145. Essentially the formatting characters (the backticks in this case) are hidden, resulting in the columns not lining up properly. If you take a look in source mode it should all line up as expected. Unfortunately there is nothing this plugin can do to resolve this issue at this time.
