### ISSUE TITLE
how to disable header

### ISSUE THREAD

**Issue by wiztensai** [tgrosinger/advanced-tables-obsidian#286]
**Describe the bug**
i want to display only content, not with colored header. how to achieve it?

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Obsidian Version: V1.4.5
 - Advanced Tables Version: 0.19.1

**Comment by tgrosinger** [comment]
Hello,
That is not something that this plugin, or Obsidian in general is able to do. It's a limitation of how tables are described in Markdown.
