### ISSUE TITLE
I hope it still works in the code block.

### ISSUE THREAD

**Issue by zhoulonghao520** [tgrosinger/advanced-tables-obsidian#289]
![image](https://github.com/tgrosinger/advanced-tables-obsidian/assets/144794808/0d6c435c-460f-4235-b509-bbe3c83e8ccb)

I hope it still works in the code block.

Maybe some people don't need this feature, it's best to have switch control

**Comment by tgrosinger** [comment]
This plugin is focused on formatting Markdown tables only. It doesn't perform any actions in code blocks.
