### ISSUE TITLE
Option to pin table headers or columns

### ISSUE THREAD

**Issue by njcrowther** [tgrosinger/advanced-tables-obsidian#292]
Would love the ability to pin table columns or header rows so I can view them while scrolling vertically or horizontally. Not sure if this is possible, but would be awesome.

Love the plugin. Thanks!

**Comment by tgrosinger** [comment]
Thanks for the suggestion. Unfortunately that request is not a feature that will be added to this plugin. Please feel free to post the idea in the plugin requests section of the Obsidian forum.
