### ISSUE TITLE
Remove or conditionally skip console use

### ISSUE THREAD

**Issue by nielsbom** [tgrosinger/advanced-tables-obsidian#296]
Currently there's [13 places](https://github.com/search?q=repo%3Atgrosinger%2Fadvanced-tables-obsidian+console&type=code) where a `console.` method is called. 

I suggest (1) removing these or (2) conditionally skipping them when in development.

For (2) I personally use a pattern of setting a `DEBUG` boolean somewhere in the root of a project and then having a function that wraps `console.log` (and the others) but only does something when `DEBUG === true`.

I can make a PR if you want.

**Comment by tgrosinger** [comment]
I agree that they should be removed. A pull request would be welcome!

**Comment by tgrosinger** [comment]
Fixed in upcoming release.
