### ISSUE TITLE
TBLFM from formulas.md not working :open_mouth: 

### ISSUE THREAD

**Issue by axaluss** [tgrosinger/advanced-tables-obsidian#299]
migrated from: https://github.com/tgrosinger/md-advanced-tables/issues/71 

using example from here: 
https://github.com/tgrosinger/md-advanced-tables/blob/main/docs/formulas.md

it's not working at all. in any of those view modes.
![image](https://github.com/tgrosinger/md-advanced-tables/assets/342630/c9d5691c-5bfa-48d4-bb71-3df13eef9884)
![image](https://github.com/tgrosinger/md-advanced-tables/assets/342630/c6f4d95d-4bac-4445-8ec6-3635c2068233)

`obsidian 1.4.16`
`advanced tables 0.19.1`
plugins: 
```json

[
  "obsidian-advanced-uri",
  "auto-classifier",
  "auto-glossary",
  "canvas-filter",
  "obsidian-checklist-plugin",
  "code-styler",
  "copilot",
  "obsidian-custom-frames",
  "dataview",
  "obsidian-day-planner",
  "obsidian-dictionary-plugin",
  "cm-editor-syntax-highlight-obsidian",
  "obsidian-find-and-replace-in-selection",
  "obsidian-full-calendar",
  "homepage",
  "obsidian-kanban",
  "obsidian-linter",
  "mermaid-tools",
  "obsidian-mind-map",
  "nldates-obsidian",
  "oz-image-plugin",
  "periodic-notes",
  "obsidian-read-it-later",
  "obsidian-reminder-plugin",
  "obsidian-rollover-daily-todos",
  "tag-wrangler",
  "obsidian-tagfolder",
  "obsidian-tasks-plugin",
  "obsidian-version-history-diff",
  "obsidian-task-archiver",
  "obsidian-pandoc",
  "obsidian-regex-replace",
  "quickadd",
  "omnisearch",
  "obsidian-auto-link-title",
  "obisidian-note-linker",
  "obsidian-latex",
  "obsidian-emoji-toolbar",
  "dbfolder",
  "table-editor-obsidian"
]
[
  "file-explorer",
  "global-search",
  "switcher",
  "graph",
  "backlink",
  "canvas",
  "outgoing-link",
  "tag-pane",
  "page-preview",
  "templates",
  "note-composer",
  "command-palette",
  "editor-status",
  "bookmarks",
  "outline",
  "word-count",
  "file-recovery",
  "sync"
]
```

**Comment by khorton** [comment]
Please confirm that you have clicked the "fx" icon in the Advanced Tables pane.   The formulae are only evaluated when you click that icon

**Comment by Anita219** [comment]
I've run into the same problem. I've clicked on the fx icon several times (in view and in source mode), no changes. 

---
my specs:

obsidian v1.4.16 (on ubuntu), advanced tables: 0.19.1

core plugins:
[
  "file-explorer",
  "global-search",
  "switcher",
  "graph",
  "backlink",
  "canvas",
  "outgoing-link",
  "tag-pane",
  "page-preview",
  "templates",
  "note-composer",
  "command-palette",
  "editor-status",
  "markdown-importer",
  "random-note",
  "outline",
  "word-count",
  "slides",
  "file-recovery",
  "sync"
]

community plugins:
[
  "calendar",
  "highlightr-plugin",
  "periodic-notes",
  "obsidian-annotator",
  "dataview",
  "obsidian-minimal-settings",
  "obsidian-timestamp-notes",
  "table-editor-obsidian"
]

**Comment by axaluss** [comment]
I clicked the button and it inserted the sum. 

I did not see the need to click the button in the [documentation](https://github.com/tgrosinger/md-advanced-tables/blob/main/docs/formulas.md).e

To confirm, I actually have to manually update the formula by clicking the button every time? If that's the case, is there a way to do this automagically? Otherwise i'll always feel suspicious that i forgot to click the button... and turn off the stove...

**Comment by khorton** [comment]
Yes, you need to click the Fx button anytime you have changed any of the inputs to the formula. There is no automagic way to avoid this. I agree that it is far from ideal, but that is the way ot works :(

**Comment by tgrosinger** [comment]
Thanks for helping with this @khorton.

This plugin is going to stick with running formulas manually for now.

**Comment by avinashkanaujiya** [comment]
| T | S | D | T | diff | Sup. & Res. | R:R | Score |
| --- | --- | --- | --- | --- | --- | --- | --- |
| X | BBBBB | +ve | 10 | 2 | 5 | 2.3 |  |
| X2 | DDDD | +ve | 0 | 5 | 5 | 1.1 |  |

`
`

This formula is not getting executed correctly. Can anyone point out what is the issue here. @tgrosinger
