### ISSUE TITLE
Asian language support

### ISSUE THREAD

**Issue by lillianhorin** [tgrosinger/advanced-tables-obsidian#30]
**Describe the bug**
The padding does not properly align the tables when using an Asian language

**To Reproduce**
1. Create a table.
2. Type in an Asian language (I am typing in Japanese)
3. Hit enter to align the columns
4. See error (screenshots below)

**Expected behavior**
The lines designating the columns align properly when typing in an Asian language.

**Screenshots**
Without monospace font checked (default monospace font)
![image](https://user-images.githubusercontent.com/24489520/99865176-f1a19a80-2b75-11eb-9320-e5484c8e9606.png)

With monospace font checked
![image](https://user-images.githubusercontent.com/24489520/99865174-e6e70580-2b75-11eb-9fbc-4a42faf3bfc4.png)

**Desktop (please complete the following information):**
OS: Windows
Obsidian version: v0.9.16
Advanced Tables Version: v0.6.0

**Additional context**
I haven't tested this on other Asian languages, only Japanese, but I would expect the issue to be the same with languages using different alphabets as well.

**Comment by tgrosinger** [comment]
@lillianhorin would you be willing to try the [Sarasa font](https://github.com/be5invis/Sarasa-Gothic) as mentioned in [this comment](https://github.com/tgrosinger/advanced-tables-obsidian/issues/16#issuecomment-723296350). If you install that font and then set it as the preferred monospace font in the Advanced Tables settings page, it will hopefully fix that issue.

Let me know how it goes please.

**Comment by lillianhorin** [comment]
@tgrosinger Thanks for the suggestion. I'll try to install, though I'm not very programming savvy and installing the dependencies for the font is already quite complicated. I wish I was more technically savvy! But I'll try my best.

**Comment by tgrosinger** [comment]
I'm pretty sure you can ignore the instructions about building (all the `npm` stuff). You can download the built fonts from the releases page: https://github.com/be5invis/Sarasa-Gothic/releases

**Comment by lillianhorin** [comment]
@tgrosinger Ah thank you for providing the release link. This worked! 

Perhaps as a heads up for future documentation: I am using kepano's Minimal Theme Settings Plugin, so rather than editing `obsidian.css` directly, I just added it to the Custom Monospace Font box.

![image](https://user-images.githubusercontent.com/24489520/99868050-076e8a00-2b8d-11eb-88b6-f34b92b46502.png)

**Comment by tgrosinger** [comment]
Oh nice, that works! You can also use this field if you want to just use that font on tables:

![MonospaceFont](https://user-images.githubusercontent.com/597386/99868312-4ba26000-2b76-11eb-854c-da8a89982f6e.png)

**Comment by milla** [comment]
I cannot find the setting in the option, I'm using the latest version of the plugin.

<img width="835" alt="image" src="https://user-images.githubusercontent.com/297531/154835189-5e013b4a-17c6-48d2-b25f-6a8337d2d916.png">

**Comment by knwng** [comment]
> I cannot find the setting in the option, I'm using the latest version of the plugin.
> 
> <img alt="image" width="835" src="https://user-images.githubusercontent.com/297531/154835189-5e013b4a-17c6-48d2-b25f-6a8337d2d916.png">

Hi @milla , you can change fonts in Preferences -> Appearance -> Font -> Monospace Font.
