### ISSUE TITLE
Toggle Context Menu

### ISSUE THREAD

**Issue by Schaschia** [tgrosinger/advanced-tables-obsidian#302]
**Describe the bug**
Open table controls toolbar hotkey (Shift+Ctrl+D) will only open, not close the context menu.

**To Reproduce**
1. Use the hotkey
2. Menu pops up to the right.
3. Try and close it with a button, you can't?

**Expected behavior**
I expected the Hotkey to be a toggle function but even if it's only to open the menu I can't find an option to close it. This might be an issue with my theme Mado Miniflow (it blends out any x buttons.) but a toggle feature would be nice nonetheless.

**Screenshots**

**Desktop (please complete the following information):**
 - Win 10
 - Obsidian Version: v1.4.16 
 - Advanced Tables Version: v0.19.1

![image](https://github.com/tgrosinger/advanced-tables-obsidian/assets/107630509/7c6c1ea0-6bd6-49aa-b290-e5dfc84d58b2)

**Comment by Denyerec** [comment]
Is the display of an actual toolbar rather than a side panel theme dependent ? I'm running a very vanilla Obsidian and when I hit the key combo I get the side panel popping up, rather than the toolbar which is shown in the Help video here on github.

**Comment by tgrosinger** [comment]
The toolbar in the video was removed a while ago, the video just needs to be updated.

You can close the sidebar with the table controls by right clicking on the icon header above it and clicking "Close".
