### ISSUE TITLE
in-cell multiline

### ISSUE THREAD

**Issue by cirtetion** [tgrosinger/advanced-tables-obsidian#303]
**Is your feature request related to a problem? Please describe.**
This is both a feature request and the solution I'm using for the time being.
I was trying to create multiline cell, and more specifically, controlling where the line does break.

**Describe the solution you'd like**
I think some kind of marker like the \\\ in latex for matrices and arrays would be a good option.

**Describe alternatives you've considered**
I'm using preview links ![[ to the content I wish to control, and have access to the normal features of obsidian, but I lose actual content of the cell (meaning the document itself doesn't contain the text and line control)

**Additional context**
WARNING : the following content comes from ANSYS documentation, and is their full intellectual property. Though is is downloadable from the official site, I do not hold any authorship nor responsibility towards neither the accuracy nor the implication of the text showed.
![image_2023-12-05_115449817](https://github.com/tgrosinger/advanced-tables-obsidian/assets/148191841/2ffc4ade-3c4d-4db6-ae10-01e6371695b0)

**Comment by tgrosinger** [comment]
Please see #215, #300.
