### ISSUE TITLE
Visual width of cells is inconsistent with Japanese text

### ISSUE THREAD

**Issue by grepgrok** [tgrosinger/advanced-tables-obsidian#304]
Japanese (and probably other languages too) text doesn't fall nicely into the monospaced sizing so you get a lot of inconsistency of how many spaces are needed. It may even require fractional spaces to get the bars to exactly line up.

This may be more of a font issue that table editing should be using some whole integer spaced font for all characters (which may be more of a Obsidian issue)

<img width="389" alt="Screenshot 2023-12-06 at 3 03 40 PM" src="https://github.com/tgrosinger/advanced-tables-obsidian/assets/43812015/46ce418b-99a4-49c5-ad67-6095386f1ea9">

**Comment by tgrosinger** [comment]
Please see #30.
