### ISSUE TITLE
Cell width fails to account for disappearing characters

### ISSUE THREAD

**Issue by grepgrok** [tgrosinger/advanced-tables-obsidian#305]
With Obsidian's autorendering in edit mode, some characters end up disappearing if you are not focussing on them (such as `\`). The spacing is fine when the text is fully expanded but you end up with jagged edges after you focus off

<img width="233" alt="Screenshot 2023-12-06 at 3 11 47 PM" src="https://github.com/tgrosinger/advanced-tables-obsidian/assets/43812015/6a1abe46-05e0-46c4-bd4d-9ef3965a6f48">
<img width="374" alt="Screenshot 2023-12-06 at 3 04 09 PM" src="https://github.com/tgrosinger/advanced-tables-obsidian/assets/43812015/572c4642-a632-4993-9f3d-889092396725">

**Comment by ParkerRobb** [comment]
I'm encountering the same problem.

**Comment by tgrosinger** [comment]
Please see #145.
