### ISSUE TITLE
[[ internal links | aliases ]] issue in tables' columns

### ISSUE THREAD

**Issue by santiyounger** [tgrosinger/advanced-tables-obsidian#31]
**Thanks for the amazing plugin, if it wasn't for this awesome plugin I was still going to emacs to create tables.** Really happy to be able to make great tables from Obsidian.

I discovered an issue when it comes to using links with  aliases inside links. in the form of something like: `[[2020-11-25|today]]`

here's an example table that works without any issues. 

```
| day            | mood    |
| -------------- | ------- |
| [[2020-11-22]] | 5/5     | 
| [[2020-11-23]] | 4/5     | 
| [[2020-11-24]] | 5/5     | 
```

| day            | mood    |
| -------------- | ------- |
| [[2020-11-22]] | 5/5     | 
| [[2020-11-23]] | 4/5     | 
| [[2020-11-24]] | 5/5     | 

but if I use this format `[[2020-11-25|today]]` with the `|` vertical line, the table confuses it for a table division line.

## Expected Behaviour
this is how I would like the table to format the last row.

```
| day                   | mood    |
| --------------------- | ------- |
| [[2020-11-22]]        | 5/5     | 
| [[2020-11-23]]        | 4/5     |
| [[2020-11-24]]        | 5/5     |
| [[2020-11-25|today]]  |         |
```
## Current Behaviour
but currently, after pressing tab to format things the `today]]` section gets' split into the wrong column.

```
| day            | mood    |
| -------------- | ------- |
| [[2020-11-22]] | 5/5     | 
| [[2020-11-23]] | 4/5     | 
| [[2020-11-24]] | 5/5     | 
| [[2020-11-25   | today]] |
```

| day            | mood    |
| -------------- | ------- |
| [[2020-11-22]] | 5/5     | 
| [[2020-11-23]] | 4/5     | 
| [[2020-11-24]] | 5/5     | 
| [[2020-11-25   | today]] |

## Specs

Linux Manjaro XFCE
Obsidian 0.9.17
Advanced Tables Version: 0.6.2

---

## Edit
 After thinking about it, this might not be a bug, but more of a request. *(Feel free to relabel it)*

 Since this is something that would happen with tables inside of Obsidian without the plugin. If anything is more of a conflict of syntax.

Would really appreciate it if there was a way to work around this issue from within the plug in.

Thank you so much

**Comment by tgrosinger** [comment]
Oh yeah, that is definitely a problem. I think this needs to be split into two problems:

1. While editing, this plugin things that the `|` in the link denotes a new column, and will format the table accordingly
2. When the markdown is rendered, Obsidian thinks the `|` in the link denotes a new column, and renders the table incorrectly

I will work on fixing the first issue, but even with that fixed, the second issue will still persist. Maybe you can post the second issue in the forums or chat?

**Comment by santiyounger** [comment]
thanks @tgrosinger appreciate you taking a look at this.

Sounds good, if you can take a look from the plugin's side of things, and I'll make a post on the forum, just to make sure I post it right in the obsidian forum, would you say it's an obsidian bug, or a feature request?

Thanks!

**Comment by tgrosinger** [comment]
I think it's probably a bug, because they extended the Markdown syntax and in doing so introduced a bug in the rendering code.

**Comment by santiyounger** [comment]
got you, I'll report it in the forum as a bug, thanks!

**Comment by santiyounger** [comment]
Reported it here in the obsidian forum 
[[[ internal links | aliases ]] issue in tables' columns - Bug reports - Obsidian Forum](https://forum.obsidian.md/t/internal-links-aliases-issue-in-tables-columns/9098)

Thanks

**Comment by santiyounger** [comment]
apparently this can be easily solved with a `\` before the `|`
like so `[[2020-11-25\|today]] `

```
| day                   | mood    |
| --------------------- | ------- |
| [[2020-11-22]]        | 5/5     | 
| [[2020-11-23]]        | 4/5     |
| [[2020-11-24]]        | 5/5     |
| [[2020-11-25\|today]]  | 5/5    |
```
| day                   | mood    |
| --------------------- | ------- |
| [[2020-11-22]]        | 5/5     | 
| [[2020-11-23]]        | 4/5     |
| [[2020-11-24]]        | 5/5     |
| [[2020-11-25\|today]]  | 5/5    |

This solves it for me

Thanks for the help!

**Comment by tgrosinger** [comment]
Oh great. Thanks for reporting back.

**Comment by santiyounger** [comment]
thank you for taking the time to look at this, thanks for the great plugin!
