### ISSUE TITLE
Tables not being created even though I've enabled the plugin

### ISSUE THREAD

**Issue by amerivietcycles** [tgrosinger/advanced-tables-obsidian#310]
**Describe the bug**
The advanced tables will not start creating even once I've entered "|" and then put in a header and then pressed tab.

**To Reproduce**

**Expected behavior**

I expected a table to be created as shown in the example video.

**Screenshots**

**Desktop (please complete the following information):**
 Windows
 - Obsidian Version: [e.g. v0.9.10] (Settings → About → Current Version)
 1.5.3
 - Advanced Tables Version: [e.g. 0.4.0] (Settings → Third-party plugin → Browse → Advanced Tables → currently installed)
0.20.0

**Additional context**

**Comment by MockingMockingBird** [comment]
Check if Live Preview is on.

Settings -> Editor -> General

**Comment by tgrosinger** [comment]
You need to type out a little more of the table now before it will start automatically creating columns and rows.

```
| Column 1 | Column 2 |
| --- |
```

After that point it should work properly.

**Comment by amerivietcycles** [comment]
Fantastic. Thank you!

**Comment by amerivietcycles** [comment]
Hi there,

I'm still having issues. I've already enabled live preview and advanced
tables; however, a new column is still not being created when I press
"tab." I've followed the instructions in github but I'm not sure what's
going wrong. Thank you!

Best,

**Comment by Li-Mingshuang** [comment]
> You need to type out a little more of the table now before it will start automatically creating columns and rows.您现在需要在表格中输入更多内容，然后表格才会开始自动创建列和行。
> 
> ```
> | Column 1 | Column 2 |
> | --- |
> ```
> 
> After that point it should work properly.之后它应该可以正常工作。

Will you repair it to make it like before?

**Comment by Cllapaodaoaer** [comment]
Yes, please fix this giant issue which just cost me 45 minutes. I created an obsidian forum account and this account to report this _bug_. The _error_ has been problematic lately.

My current workaround: Creating a template to input the above table thing. 

If you insist on keeping it this way, could we please have a button or hotkey to create a table instead of typing this out every time? I understand if this is a workaround for some larger bug but wow this has been kind of a pain. :(


In other news, thanks for making the (otherwise) tremendously helpful plugin. :)

**Comment by Cllapaodaoaer** [comment]
Just posted in the other thread linked above. Yes, please fix, and/or give us the option with a toggle, "create table" hotkey or something. Big oof. :(

(Thanks again for making the plugin in the first place though.)

**Comment by drozd2000** [comment]
> Yes, please fix this giant issue which just cost me 45 minutes. I created an obsidian forum account and this account to report this _bug_. The _error_ has been problematic lately.
> 
> My current workaround: Creating a template to input the above table thing.
> 
> If you insist on keeping it this way, could we please have a button or hotkey to create a table instead of typing this out every time? I understand if this is a workaround for some larger bug but wow this has been kind of a pain. :(
> 
> In other news, thanks for making the (otherwise) tremendously helpful plugin. :)

you can use 
<html>
<body>

editor:insert-table | Insert table
-- | --



</body>
</html>
