### ISSUE TITLE
Tab and Enter do not create new columns and new rows respectively

### ISSUE THREAD

**Issue by MockingMockingBird** [tgrosinger/advanced-tables-obsidian#311]
**Describe the bug**
_Version 0.20.0_
Tab and Enter do not create new columns and new rows respectively. 

**To Reproduce**
1. Open Settings > Third-party plugin
Make sure Safe mode is off
2. Click Browse community plugins
3. Search for "Advanced Tables" -> Click Install
4. Close the community plugins window and activate plugin
5. Close Obsidian then right click on the app to "quit"
6. Once reopened create a new note add a title then enter 
```| test ``` then press either ```tab``` or ```enter``` and it just tabs the ```| test ``` over

The advanced tables UI recognizes the ```| test``` as a table and lets me use it to edit the table but that's not really a solution I want to have to rely on.

**Expected behavior**
Hotkey | Action
-- | --
Tab | Next Cell
Shift + Tab | Previous Cell
Enter | Next Row

**Screenshots**
<img width="758" alt="image" src="https://github.com/tgrosinger/advanced-tables-obsidian/assets/60328345/b7909cdb-212d-4f5f-af0d-ca1e52b3eb0b">

<img width="724" alt="image" src="https://github.com/tgrosinger/advanced-tables-obsidian/assets/60328345/eda72b49-d938-44e1-88f3-0ac9ba4510af">

<img width="1093" alt="image" src="https://github.com/tgrosinger/advanced-tables-obsidian/assets/60328345/959238fe-e5db-40af-ad8c-a5ecbd564c12">

**Desktop (please complete the following information):**
 - OS: Mac OS Sonoma 14.2.1
 - Obsidian Version: 1.5.3
 - Advanced Tables Version: 0.20.0

**Additional context**
I tried turning all other community plug-ins off to fix the issue but that didn't help.

**Comment by MockingMockingBird** [comment]
Live preview was on which isn't supported!

**Comment by santhoshsram** [comment]
I believe tab and enter used to work with live preview on as well in pre v1.5 of Obsidian. 1.5 adds a new table editor natively which also has tab actions. Advanced plugin autoformatting (on tab and enter) stopped working for me right after I updated to Obsidian 1.5.3.

Suspecting if the behavior reported here is related to the table editor in Obsidian 1.5. JFYI.

**Comment by toprak** [comment]
I changed my mode live preview to source mode still same.

**Comment by inkyunp** [comment]
I had same problem. I solved it by turn off 'Show Indentation Guides'

**Comment by santhoshsram** [comment]
Just disabling live preview seems sufficient to enable the `tab` and `enter` key behavior for Advanced Tables. Enabling or disabling `Show Indentation Guides` does not seem to have any effect on the behavior of these two keys. With live preview enabled  `tab` and `enter` keys do not automatically format the table as they used to previously.

OS: MacOS Sonoma 14.4
Obsidian Version: 1.5.11
Advanced Tables Version: 0.21.0

**Comment by santhoshsram** [comment]
> Rolling back to version v0.19.1 can solve this problem

Is there a way to rollback from the Obsidian app or do I have update the plugin folder manually?

**Comment by Barnette-ao** [comment]
> I had same problem. I solved it by turn off 'Show Indentation Guides' and live preview.
> 
> OS: Mac OS Sonoma 14.2.1 Obsidian Version: 1.5.8 Advanced Tables Version: 0.21.0

this operation has solved the promblem in my computer

Obsdian Version 1.6.7 Advanced Tables Version:0.22.0 OS:Windows 11

**Comment by RainFung** [comment]
The issue has not been fixed yet

**Comment by Hidde-Heijnen** [comment]
Anyone got this working with live preview?

**Comment by hinog** [comment]
I have the same problem.
Switch editing mode (live preview to source mode) does not work for my problem.

Obsidian version: v1.8.10
Advanced tables version: 0.22.1
OS: windows11 Home 24H2
