### ISSUE TITLE
[Sorting] "group by path + sort by path reverse" does not reverse order

### ISSUE THREAD

**Issue by parties** [tgrosinger/advanced-tables-obsidian#318]
**Describe the bug**
I have my daily notes in a folder like `Time/Days/2024-01-01`, and I have tasks listed on those days. When I use the following query, the tasks are not sorted by path in reverse order:

```
not done
path includes Time/Days
sort by path reverse
group by path
```

I have tried putting the `group by path` _before_ the `sort by path reverse` and both produce the same output (which is a list of tasks grouped by file, but the paths are in increasing order, like `Time/Days/2024-01-01`, `Time/Days/2024-01-02`, `Time/Days/2024-01-03`, ...).

**To Reproduce**
Try querying for tasks in your own daily notes folder and have it sort by reverse path.

```
path includes <your path to daily notes>
sort by path reverse
group by path
```

**Expected behavior**
The expected sort order would be:
- `2024-01-03`
- `2024-01-02`
- `2024-01-01`

**Screenshots**

Query used in screenshot:
```
not done
path includes 01-Time/Days
sort by path reverse
group by path
```

![image](https://github.com/tgrosinger/advanced-tables-obsidian/assets/6612736/7b78b0bd-56c3-464f-8d38-bd044c861d90)

**Desktop (please complete the following information):**
 - OS: Mac OS 13.5
 - Obsidian Version: `1.5.3`
 - Advanced Tables Version: `6.0.0`

**Additional context**
I absolutely love this plugin, _thank you for making it._ 🙌

Let me know if you need any additional context.

**Comment by tgrosinger** [comment]
Hello,
It looks like you're talking about the Obsidian Tasks plugin. Please file this issue over there for them to look at. Thank you.

**Comment by parties** [comment]
My goodness, my apologies, thank you.
