### ISSUE TITLE
Format all tables in a note

### ISSUE THREAD

**Issue by DutchPete** [tgrosinger/advanced-tables-obsidian#32]
**Is your feature request related to a problem? Please describe.**

*I have a template with a number of tables in it. If I want to prettify all the tables I have to put my cursor in every one of them in turn and use the plug-in command "Format table at cursor".*

**Describe the solution you'd like**

*To be able to prettify all the tables in the note in 1 go, like with a hotkey.*

**Comment by tgrosinger** [comment]
Hi @DutchPete, good idea. This will be in the next release. There is no hotkey assigned by default, but you can assign one in the HotKeys settings page. Just search for "Format all tables"

**Comment by DutchPete** [comment]
Many thanks, I look forward to it as it will make life a lot easier 😄

**Comment by DutchPete** [comment]
This issue is closed but I do want to thank you again, Tony.
