### ISSUE TITLE
Hotkeys start blank

### ISSUE THREAD

**Issue by BradAlt** [tgrosinger/advanced-tables-obsidian#34]
**Describe the bug**
I expected the default hotkeys referenced in the github to be initialized but instead they are all blank.
Literally not even a problem and easy to fix in like 5 seconds, but I felt it was right to throw it on the bug tracker

**To Reproduce**
1. Download and activate
2. Profit

**Expected behavior**
I expected Tab to start making a table right away, and for the other hotkeys to be bound

**Screenshots**
![My Hotkeys](https://user-images.githubusercontent.com/54485108/100871093-af2d6700-346d-11eb-8efa-9879a036fa9f.png)
vs
![Expected Hotkeys](https://user-images.githubusercontent.com/54485108/100871234-ec91f480-346d-11eb-8255-e768b2c9ddb9.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20
 - Obsidian Version: v0.9.17
 - Advanced Tables Version: v0.7.0

**Extra Information**
Something in general is being very odd with my Obsidian at the moment. I cant edit the hotkeys at all.
Will update after restart.

**Comment by tgrosinger** [comment]
Hey @BradAlt, these hotkeys allow you to set the commands to something other than tab/shift+tab/enter/shift+enter. It's recommended that you only use them if you disable these options:

![Screenshot 2020-12-02 123358](https://user-images.githubusercontent.com/597386/100928116-bbe9a380-34dd-11eb-87c2-522f68650646.png)

To start making a table, press pipe (`|`) then enter the first header content, then tab. Take a look at the demo in the README.md for an example.

I'll close this issue for now, but if this doesn't answer your question then please re-open.
