### ISSUE TITLE
Plugin sometimes deletes everything in document

### ISSUE THREAD

**Issue by Grezzo** [tgrosinger/advanced-tables-obsidian#340]
**Describe the bug**
Plugin seems to randomly delete everything in my document

**To Reproduce**
Enable plugin, use obsidian, notice some time later that everything in the open document has gone. Press CMD+Z to undo it's deletion.

**Expected behavior**
Not deleting everything in the document

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 14.6.1
 - Obsidian Version: 1.6.7
 - Advanced Tables Version: 0.22.0

**Additional context**
This doesn't happen when I have the plugin disabled so to work around it, I only enable it while I need the features it add, then I disable it until I need it again.

**Comment by tgrosinger** [comment]
Hi @Grezzo, this is the first I have heard about this issue and there haven't really been any changes to this plugin in the last couple years.

Can you please tell me what you are doing when this plugin clears the contents of the file? Please provide instructions on how to reproduce the issue so I can better track down the problem.

**Comment by Grezzo** [comment]
I have found that this still happened after I disabled the plugin so it's not the plugin's fault.

My apologies
