### ISSUE TITLE
Wrap cell content when using readable line length mode

### ISSUE THREAD

**Issue by archelpeg** [tgrosinger/advanced-tables-obsidian#35]
**Is your feature request related to a problem? Please describe.**
I quite often have a lot of text in tables. In conjunction with readable line length it does not adapt to it but instead continues indefinitely in edit mode.

**Describe the solution you'd like**
I would like the content of the cells in edit mode to wrap just like normal text in Obsidian does so that the width of the page is not exceeded.

**Describe alternatives you've considered**
No alternatives I can think of.

**Additional context**

**Comment by tgrosinger** [comment]
There is unfortunately not a good solution for long lines or multi-line cells in markdown tables. I think it's one of their biggest short-falls.

If the solution you are looking for is to just have the readable line-length apply to tables, then I think the best option would be to put css snippet in your `.obsidian/snippets` folder to change that.

I don't know what the css for that is, but I'll see if I can find out for you 🙂

**Comment by tgrosinger** [comment]
I think this might work, but like I mentioned I am not sure that it will actually look very good.

```
.CodeMirror-wrap pre.CodeMirror-line-like {
  white-space: pre-wrap !important;
}
```

**Comment by DutchPete** [comment]
@tgrosinger: I am also interested in this issue, and have put your code in my css but it is not just that the note in Edit mode does not look good, the code does not work (version 0.7.0).

I guess there is no solution then.

**Comment by tgrosinger** [comment]
It may be worth asking for suggestions in Discord or the forum. CSS is not my strongest point.
Sorry for the lack-luster answer.
