### ISSUE TITLE
Failed to load plugin table-editor-obsidian

### ISSUE THREAD

**Issue by jonasdiemer** [tgrosinger/advanced-tables-obsidian#36]
**Describe the bug**
Plugin doesn't load - any help appreciated.

**To Reproduce**
1. Install plugin
2. Click on slider to enable plugin
3. See popup "Failed to load plugin table-editor-obsidian"

**Desktop (please complete the following information):**
 - OS: macOS Big Sur on M1
 - Obsidian Version: v0.9.20
 - Advanced Tables Version: 0.7.0

**Comment by tgrosinger** [comment]
Can you please provide me any output from the console? You can open it by pressing command+option+i in Obsidian. Click on "Console" in the drawer that opens, then make sure verbose logs are on. See the image below:

<img width="783" alt="verbose-logs" src="https://user-images.githubusercontent.com/597386/101969832-7f076600-3bdb-11eb-8e7f-2bd344a2c3d2.png">

**Comment by jonasdiemer** [comment]
Please find the log attached - let me know if anything else would help to pinpoint the issue.
[obsidian.md-1607875269672.log](https://github.com/tgrosinger/advanced-tables-obsidian/files/5684921/obsidian.md-1607875269672.log)

**Comment by tgrosinger** [comment]
Hi @jonasdiemer,
This is very helpful, thank you.

```
app.js:1 Plugin failure: obsidian-mind-map Error: ENOENT: no such file or directory, open '/Users/jonasdiemer/SynologyDrive/Dropbox/Vault/.obsidian/plugins/obsidian-mind-map/main.js'
  3 (anonymous) @ app.js:1
  4 app.js:1 Plugin failure: table-editor-obsidian Error: ENOENT: no such file or directory, open '/Users/jonasdiemer/SynologyDrive/Dropbox/Vault/.obsidian/plugins/table-editor-obsidian/main.js'
  5 (anonymous) @ app.js:1
```

It looks like the Advanced Tables plugin and the Mind Map plugin were both installed incorrectly. Did you install them using the plugin browser inside Obsidian? If you installed them by downloading files directly from Github I would recommend instead installing them through Obsidian as it will make sure all the correct files are in place.

Let me know if that gets it working 🙂

**Comment by jonasdiemer** [comment]
Hi,

thanks for the quick response - I installed both from within Obsidian via the Community Plugins Browser.

Any other idea? I'll try moving my vault outside of my Synology drive folder.

**Comment by jonasdiemer** [comment]
<img width="435" alt="Screen Shot 2020-12-13 at 17 16 17" src="https://user-images.githubusercontent.com/1502748/102017379-f3badb80-3d66-11eb-99e9-ad43d26d210e.png">

Same issue with Vault in Documents folder...

**Comment by tgrosinger** [comment]
Please delete the directory `/Users/jonasdiemer/SynologyDrive/Dropbox/Vault/.obsidian/plugins/table-editor-obsidian` and try installing it again. For some reason that installation is missing files.

**Comment by jonasdiemer** [comment]
I tried that a few times without luck. While downloading the release from GitHub (in an attempt to populate the directory myself), I noticed the files suddenly "appeared" on their own. So seems it's working now.

Let me know if you'd like me to try out anything to identify a potential issue...

**Comment by tgrosinger** [comment]
Oh great. That's strange, I wonder what happened.

I just uninstalled the plugin myself and reinstalled it and it seems to be working. I think if it's working for you then let's call this a fluke and close the issue 🙂

**Comment by TrillStones** [comment]
当你使用ss的pac模式时，编辑user rules（Edit User Rules For PAC），把下面这条加进去，因为obsidian读取插件列表的时候，是访问以下的域名：

||raw.githubusercontent.com^
