### ISSUE TITLE
How to escape from table

### ISSUE THREAD

**Issue by visualcurrent** [tgrosinger/advanced-tables-obsidian#38]
If you start a document with a table, we're trapped. There's no practical way to get out of the table. 

I can think of two relatively intuitive approaches to fix this:

- A simple keyboard shortcut to modify `Enter` to work as "Obsidian Normal" would be very convenient. Shift-Enter or Ctrl/Cmd-Enter are common `Enter` key modifiers and seems ideal to add a normal line feed. (Shift-Enter conflicts less with Obsidian than Ctrl-Enter)
- Or slightly less convenient but still okay. Pressing Enter when at the very beginning of a line (technically outside of the table) acts as a normal line feed. Just requires a couple backspaces or back-arrows before hitting `Enter` to exit a table (then delete the extra line of pipes).

My workarounds were navigating somewhere else, copy a couple lines, then come back and paste over the table to escape it. Then delete the copied junk. Eventually I discovered that I can backspace to the start of a line, type come characters, then press return. Then there's enough space to escape the table and delete the extraneous stuff. Or I could think ahead and make sure to add some line feeds before creating a table. But thinking ahead rarely happens ;) 
(we shouldn't have to think ahead. tools that encourage flow is more important)

Thanks though. I really like this plugin. Great work!

**Comment by tgrosinger** [comment]
Hi @visualcurrent,
There is a command called "Move cursor out of table" which will put your cursor on the line after the table, creating it if required. I think that will do what you are looking for.

<img width="704" alt="Move Cursor" src="https://user-images.githubusercontent.com/597386/102038942-7328c900-3dc0-11eb-8987-c554d92e8237.png">

You can bind the hotkey to anything you like. I would recommend something like <kbd>shift</kbd>+<kbd>escape</kbd>.

**Comment by visualcurrent** [comment]
That works great! 

I had missed the "search Advanced Tables" suggestion in your docs.

**Comment by visualcurrent** [comment]
However, do you have any suggestion for when the Table is at the top of a page. It is bothersome how stuck we are in that position if we want to add content above the table. 

Adding a normal linefeed to the commands for your table plugin would solve all of it. It would also facilitate easily splitting a table, or creating a new table in the same format.

**Comment by tgrosinger** [comment]
Hmm, I will have to think about this some more. The plugin has a lot of commands already, so I want to make sure any new ones being added are done right.

FWIW when using Vim mode in Obsidian, you can insert a new line above the table by pressing <kbd>shift</kbd>+<kbd>O</kbd> from normal mode.

**Comment by robert-taylor-maersk** [comment]
There's a simple workaround:

1. Select all (CTRL-A)
2. Cut  (CTRL-X)
3. Add a couple of blank lines to your (now empty) documnet.
4. Position the cursor between the blank lines
5. Paste (CTRL-V)

**Comment by DutchPete** [comment]
@robert-taylor-maersk: how obvious, how simple, how easy. Thanks for reminding us.

**Comment by visualcurrent** [comment]
@robert-taylor-maersk I like that. Simple, pretty quick, and rarely do I have so much text that this would be any issue.

**Comment by tgrosinger** [comment]
@visualcurrent you can also use shift+enter to jump to the line after the table.
There is not a way to jump to a line before the table though.
