### ISSUE TITLE
Table navigation overrides hotkeys

### ISSUE THREAD

**Issue by BeksOmega** [tgrosinger/advanced-tables-obsidian#41]
**Describe the bug**
If you have "Bind enter to table navigation" on in the plugin settings, it will overide other keybindings such as ctrl + Enter if you are in a table.

For example, I have ctrl + enter bound to "Open link under cursor in new pane", but if I attempt to open a link inside a table using this keybind, it will instead navigate me to the next row.

**To Reproduce**
1. Go to Bind "Open link under cursor in new pane" to ctrl + enter via the hotkeys settings.
2. Paste the following table into a new note:
```
| Test | Test     |
| ---- | -------- |
| Test | [[Test]] |
```
3. Navigate the cursor (aka carrot?) "inside" the link.
4. Press ctrl + enter.
5. Observe how a new row is added to the table.

**Expected behavior**
The keybindings that are enabled via the advanced tables settings should not activate if a "special" key is pressed (eg shift, alt, ctrl).

**Screenshots**
I don't think it's necessary for this one! But if you want a gif I'm happy to provide one if asked =)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Obsidian Version: 0.9.22
 - Advanced Tables Version: 0.5.6

**Additional context**
Thanks for the great plugin =) It's very intuitive and helpful.

**Comment by tgrosinger** [comment]
@BeksOmega, thanks for the bug report. I think I can probably fix this one. I'll take a look soon.
