### ISSUE TITLE
Not quite working on a mac big sur.

### ISSUE THREAD

**Issue by davidlee321** [tgrosinger/advanced-tables-obsidian#50]
**Describe the bug**
Features that are not working: shortcut keys (tab, enter, etc.), automatic resizing of columns as I'm typing.

Some Features that are working: add column, add row, ...

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur
 - hardware: macbook pro intel chip
 - Obsidian Version: 0.10.1
 - Advanced Tables Version: 0.7.0

**Comment by tgrosinger** [comment]
Hi @davidlee321, it sounds like you are running an old version of the plugin. Please make sure you update to the latest version.

Can you provide some screenshots or screen recordings of the behavior you are seeing? Additionally, any messages you see in the console (<kbd>cmd</kbd>+<kbd>option</kbd>+<kbd>i</kbd> I believe) would be very helpful. Thanks.

**Comment by tgrosinger** [comment]
I am going to close this due to inactivity. If you are still having trouble please reopen this issue.
Thank you.
