### ISSUE TITLE
Aliases are recognized as dividers

### ISSUE THREAD

**Issue by InternetDr3am** [tgrosinger/advanced-tables-obsidian#52]
Aliases on links are recognized as two different entries when put into a table & viewed in preview mode.

1. Create a table
2. Put in the value [[Name|Alias]]
3. Switch to preview mode to view the table

The use of [[Name|Alias]] usually creates a link with an alias instead of its file name, instead it becomes two different entries when put into a table.

 - OS: Windows 10
 - Obsidian Version: v0.10.1
 - Advanced Tables Version: 0.8.0

**Comment by tgrosinger** [comment]
This sounds like the same issue as #31.

Obsidian and this plugin both require that links with an alias have a `\` before the pipe. For example `[[Name\|Alias]]`.

Let me know if that doesn't solve the issue for you.

**Comment by robertandrews** [comment]
> Obsidian and this plugin both require that links with an alias have a `\` before the pipe. For example `[[Name\|Alias]]`.

Can you clarify...

Do you mean that Obsidian, in tables, requires the `\` character to escape a non-table pipe within a table?

Because this formulation isn't required in normal text.
