### ISSUE TITLE
Wrap text in column

### ISSUE THREAD

**Issue by benmosse** [tgrosinger/advanced-tables-obsidian#54]
**Is your feature request related to a problem? Please describe.**
For columns that are more textual, long text poses a problem. A way to enable wrapping in a column would enable longer notes to be more readable.

**Describe the solution you'd like**
A additional button or ability to enable wrapping of text within a call

**Describe alternatives you've considered**
There may be a way to do this already. If so just close this and thanks for your amazing plugin.

**Comment by DutchPete** [comment]
AFAIK there is no way to do this, and some weeks ago Tony said it too. We'll have to wait for WYSIWYG.

**Comment by tgrosinger** [comment]
@DutchPete is right, there is not a way to wrap text content in edit mode of markdown.

See #35 as well.

**Comment by johans3** [comment]
Adding manually multiple lines of text to markdown tables feels like going back to stone age - I did it manually for 4 days in a row but today felt fed up. 

I've wrote my own parser in `applescript` on Mac that builds rows and columns from clipboard data
The parser was bothersome but easy to code 

Just wondering, why advanced tables doesn't ship with support for multiple lines by default.

**Comment by tgrosinger** [comment]
> Just wondering, why advanced tables doesn't ship with support for multiple lines by default.

Please feel free to contribute code to the project. I'm only a single person and can not add every feature that is requested.

**Comment by johans3** [comment]
> > Just wondering, why advanced tables doesn't ship with support for multiple lines by default.
> 
> Please feel free to contribute code to the project. I'm only a single person and can not add every feature that is requested.

As said before, I can't code in js, typescript, CSS or whatever. My code is pure `applescript`, only for Mac. I added the steps how to code it for everyone missing the point but knowing how to code. Otherwise, gladly.

**Comment by alexJhao** [comment]
I use replace space with <br> between 2 words.
the obsidian support html tag. so it will turn out to be multi-line.

**Comment by lightbluepoppy** [comment]
> I replace 'space' with `<br>` between 2 words. the obsidian support html tag. so it will turn out to be multi-line.

Please note that Markdown is just a syntax sugar of HTML. 

> Markdown applications use something called a Markdown processor (also commonly referred to as a “parser” or an “implementation”) to take the Markdown-formatted text and output it to HTML format.
https://www.markdownguide.org/getting-started/
