### ISSUE TITLE
Column misalignment with code snippets

### ISSUE THREAD

**Issue by mdelaney** [tgrosinger/advanced-tables-obsidian#56]
First, thank you for creating such a useful plugin! Table alignment in editing mode was a constant frustration before I found this. Thank you!

**Describe the bug**
When you have an inline code snippet in a cell, the column divider is misaligned.

**To Reproduce**
Simply paste the following
```md
| foo    | bar |
| ------ | --- |
| `test` |     |
```

**Expected behavior**
The column marker should be aligned

**Screenshots**
<img width="209" alt="Screen Shot 2021-01-23 at 21 23 14" src="https://user-images.githubusercontent.com/665342/105621902-43a6ac80-5dc1-11eb-9058-f9c7b3fa8d18.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur - 11.1
 - Obsidian Version: 0.10.9 (this is the same with previous versions as well)
 - Advanced Tables Version: 0.8.2

**Comment by tgrosinger** [comment]
Hmm, this is happening because the inline code changes the text size a bit when in edit mode. The only way around this would be to disable special formatting for inline code blocks. I think that would be worse than having the column a little misaligned, but curious to hear what others think.

**Comment by mdelaney** [comment]
After a bit of playing with the custom CSS option I found I could just add the following to `obsidian.css`.
```css
.HyperMD-table-row span.cm-inline-code,
pre > code:not(.prism) {
    font-size: 100%;
}
```
This seems to work as expected and only impact code snippets inside a table row (and leaves all other styling in tact). That said, I'm not terribly familiar with CSS so there may be a better way to do this.

**Comment by tgrosinger** [comment]
Nice, good find. I will put that in the plugin so others can benefit as well. Thank you.
