### ISSUE TITLE
"Cannot find a recently edited file"

### ISSUE THREAD

**Issue by luckman212** [tgrosinger/advanced-tables-obsidian#57]
- Obsidian 0.10.10
- AT plugin 0.9.1

Happy to see the new permanent table toolbar! 🎉 

One thing I noticed (not sure if it can be worked around or not)

If the toolbar is closed:
![image](https://user-images.githubusercontent.com/1992842/105900192-b5613f00-5fe9-11eb-9052-6fc25445a2ac.png)

The next time you open it (trigger via hotkey) and click any of the buttons, you will get an error _"Advanced Tables: Cannot find a recently edited file"_
![image](https://user-images.githubusercontent.com/1992842/105899677-f73db580-5fe8-11eb-870a-f86793ee636a.png)

This persists until you do one of:
- switch to another note and then back again
- reload Electron
- quit & restart Obsidian

**Comment by tgrosinger** [comment]
Thanks for the bug report.

I think I'm storing the name of the open file when a file is opened. So I just need to store the active file when the toolbar is opened too. I'll take a look soon.
