### ISSUE TITLE
Would you consider adapting the plugin to VS Code and WikiJS?

### ISSUE THREAD

**Issue by asitemade4u** [tgrosinger/advanced-tables-obsidian#58]
Hi,
I find the plugin for Obsidian absolutely outstanding.
Would you adapt it for [**Wiki.js**](https://github.com/Requarks) and **VS Code** (there are equivalents on VS Code but none as good).
Thanks.
S.

**Comment by tgrosinger** [comment]
Hi @asitemade4u. This plugin is built on top of https://github.com/tgrosinger/md-advanced-tables/ which is designed to be editor agnostic. I am not able to take on the project of learning how to make plugins for those editors, but someone else can use that library to do so!
