### ISSUE TITLE
Export to CSV or JSON

### ISSUE THREAD

**Issue by jadbox** [tgrosinger/advanced-tables-obsidian#62]
I am highly enjoying your plugin, and would love to adopt into my note taking flow. As part of my work, I need a way to export my tables to csv format to be used in scripts. Would this be possible? :)

**Comment by tgrosinger** [comment]
@jadbox, this plugin is really focused on improving the editing experience in tables. I don't think this is an unreasonable request though. I could imagine a button in the toolbar which when clicked copies the table the cursor is in to the system clipboard in csv format.

I am focusing mostly on another plugin right now, so I do not think I'll be able to add this feature in the near future. I would gladly welcome a pull request though if someone wanted to add it.

**Comment by jadbox** [comment]
@tgrosinger If you could get this PR merged into your fork of md-advanced-tables, I'll be able to get the reference to withCompletedTable to add the CSV export option. https://github.com/tgrosinger/md-advanced-tables/pull/16

Otherwise TBH, I don't really have time to try to build this out in a way that spans cross library support for CSV export. I need a public reference to withCompletedTable so that I can scan over the table to create the export from within the plugin.

**Comment by jadbox** [comment]
Started a draft PR here: https://github.com/tgrosinger/advanced-tables-obsidian/pull/65

**Comment by tgrosinger** [comment]
Wow, thanks for working on this so quickly! 😁 

I'm wondering if the function which scans over the table and create that csv should be in the md-advanced-tables repo. That function would be public, and could return the csv as a string. Then this plugin would only need to take that string and copy it to the clipboard, or maybe display in a popup modal window.

What do you think?

**Comment by jadbox** [comment]
@tgrosinger I think that's an excellent idea! However, I am at an extreme lack of time at the moment. I'd be willing to commit to doing it this way if you'd be willing to complete #65 (or start a new PR) if I do implementation of CSV export within `md-advanced-tables`. I'm much faster at working within purely JS, as I do not have experience working on plugins for Obsidian and don't even know how to test when I'm building. What do you say?

**Comment by tgrosinger** [comment]
That sounds great, I'd be be happy to do the plugin side of it.
Thanks!

**Comment by jadbox** [comment]
@tgrosinger I have done it! I've added two new methods to the `md-advanced-tables` to export either a raw two dimensional array and a method to straight export a CSV in the most common format used by most spreadsheets (tab spaces cells and newlines between rows).

Here's that PR:
https://github.com/tgrosinger/md-advanced-tables/pull/16

Thank you for offering to build on this update to update this plugin to support CSV exports. I'd recommend that there's two options added- `export with headers` and `export without headers`. :)

**Comment by tgrosinger** [comment]
Merged and released. Let me know what you think.
Thanks for your help.

**Comment by jadbox** [comment]
@tgrosinger it works perfectly! Thank you for you help good sir!
