### ISSUE TITLE
Support for creating a new table

### ISSUE THREAD

**Issue by Cito** [tgrosinger/advanced-tables-obsidian#63]
It would be nice if this add-on would also support creating a new table from scratch. You would enter the numer of rows and columns, and the Markdown table structure for an empty table would be inserted.

**Comment by tgrosinger** [comment]
@Cito, the plugin will help you build a table from scratch, it just does it using the tab and enter keys instead.

To use this, just type a single `|` then press tab the number of columns you wish to have, and then press enter the number of rows you would like. You can fill in the columns and rows as you go, or create the whole table first and then come back to edit.

**Comment by Cito** [comment]
Yeah, that's probably good enough. Maybe you should mention explicitly in the README how easy it is to create a *new* table with this add-on as well. Since the table with the commands just says action = "next cell" I assumed at a first glance these are just move operations and the cells already needs to exist, while actually they also create cells and you only need to provide the inital `|`.

The way it works, this add-on is really usefual and a great time-saver - without it, I would not want to use Markdown tables. Thanks a lot for providing this. Will go an buy you a coffee now. :)

**Comment by tgrosinger** [comment]
I'll do that.
Thanks very much!
