### ISSUE TITLE
Misaligned when input chinese

### ISSUE THREAD

**Issue by lefinite** [tgrosinger/advanced-tables-obsidian#69]
**Describe the bug**
Got problem of auto formatting when input chinese

**To Reproduce**
1. creat a table
2. input chinese
3. auto formatting

**Expected behavior**
Misaligned when input chinese

**Screenshots**
![image](https://user-images.githubusercontent.com/23370734/111127398-c45a7b80-85ae-11eb-9494-744880f95c17.png)

**Desktop (please complete the following information):**
 - OS: [Mac os]
 - Obsidian Version: v0.11.5
 - Advanced Tables Version: 0.11.0

**Comment by tgrosinger** [comment]
Hi @lefinite, thanks for the bug report. There is some support for CJK languages, but I believe most people are having the best luck using a specific font. Please check out #30.

I'm going to close this as a dup, but please reopen if that does not solve the problem for you.
