### ISSUE TITLE
Formulas working in 0.11.7 ?

### ISSUE THREAD

**Issue by luckman212** [tgrosinger/advanced-tables-obsidian#70]
Hi Tony

Trying to make basic use of the formulas, but for some reason I can't figure out if I'm not doing something right or if something's broken.

- Obs 0.11.7
- AT plugin 0.11.0
- macOS

I tried your simple example from [here](https://github.com/tgrosinger/md-advanced-tables/blob/main/docs/formulas.md#user-content-the-fomula-structure---an-overview):

![image](https://user-images.githubusercontent.com/1992842/111194460-99adfa00-8591-11eb-9f73-201514b9e8dc.png)

Not seeing any results, and no errors etc in the JS console...

**Comment by tgrosinger** [comment]
Hmm, I hate to say "works for me"... but it does.

I want to clarify, are you evaluating the formulas? Use the "Evaluate table formulas" from the command palette or click the formulas button in the toolbar.

**Comment by luckman212** [comment]
Good grief. No I didn't 😞 
I failed to read the docs.

All working fine, thank you.
