### ISSUE TITLE
Cell Misalignment with Internal Links

### ISSUE THREAD

**Issue by theSiberman** [tgrosinger/advanced-tables-obsidian#72]
Hey Mate, great plugin, I'l using it for everything! Thanks!

**Describe the bug**

When I create internal links the cells are misaligned in the edit view.

**To Reproduce**
1. Create a table.
2. Put an internal link in a cell.
3. Tab out of the cell.

**Expected behavior**
The cells to stay aligned.

**Screenshots**
![image](https://user-images.githubusercontent.com/3615840/111703558-ee9f8800-8891-11eb-9f74-df3508a05a2f.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 11.2 Big Sur
 - Obsidian Version: 0.11.5
 - Advanced Tables Version: 0.11.0

**Additional context**

**Comment by DutchPete** [comment]
Speaking of internal links in cells, I don't know if this is related or should be opened as another issue, but when I try to put this in a cell:

![image](https://user-images.githubusercontent.com/10794265/111738964-e7c14700-888a-11eb-801b-08c5961ae1bc.png)


it does not work.

**Comment by tgrosinger** [comment]
@theSiberman, it looks like your table is missing the outer pipe characters. Please try adding a `|` at the beginning of each row and then format the table (just press tab in a cell). Let me know if that takes care of it.

@DutchPete, markdown does not support multiple lines within tables, so code blocks will not work. You can however use inline-code using the single backticks.

**Comment by DutchPete** [comment]
OK Tony, thanks for your feedback.

**Comment by theSiberman** [comment]
Hey Mate,

That's just the cropped screenshot, they are there.

![image](https://user-images.githubusercontent.com/3615840/111922832-5226f100-8af0-11eb-9027-97e20798b653.png)

**Comment by tgrosinger** [comment]
@theSiberman I tested by recreating the table as you show it, but the table is formatting for me. Can you please confirm that the plugin is enabled? One way to do this would be to put your cursor in the table, then open the command palette and search for the plugin name as shown below:

![image](https://user-images.githubusercontent.com/597386/113430377-ed408600-938e-11eb-8ae5-e6dfd55262da.png)

**Comment by theSiberman** [comment]
@tgrosinger how odd! I've checked and it seems to be active.

![image](https://user-images.githubusercontent.com/3615840/113934636-5ade2d80-9839-11eb-8e83-ae37791b19fa.png)

Maybe it's conflicting with another plugin? These are the only ones I have active.

![image](https://user-images.githubusercontent.com/3615840/113934727-734e4800-9839-11eb-8c50-51f9aa48e5c3.png)

**Comment by Servinjesus1** [comment]
+1 not working for me: v0.12.5. Rows without links work correctly, while rows with links or rows with _named_ links behave erratically.

![image](https://user-images.githubusercontent.com/8541095/124523237-84184680-ddb3-11eb-96a0-6d96018fc860.png)
![image](https://user-images.githubusercontent.com/8541095/124523246-8e3a4500-ddb3-11eb-93c1-78b7b330513e.png)

**Comment by ctrlok** [comment]
Can confirm, it's not working with links like `[[linkToNote|name]]` 

I record video example

https://user-images.githubusercontent.com/3265316/126622503-61b07d19-97a6-4214-ab84-bb7a7d5b6c35.mp4

**Comment by tgrosinger** [comment]
I think the issue with renamed links is likely the same as https://github.com/tgrosinger/md-advanced-tables/issues/25

**Comment by tgrosinger** [comment]
That issue has been resolved, and the table formatting is looking normal to me. Please let me know if this issue is still happening in v0.13.0.

![image](https://user-images.githubusercontent.com/597386/127184512-54310720-751f-4c73-9572-fb3f605dd0cd.png)

**Comment by ctrlok** [comment]
Hi @tgrosinger 
Thanks for the feedback. 

`[[link \| name of link]]` is not valid wiki link syntax and is not supported by various platforms (like mkdocs). 

Symbol `|` used for changing the displayed text of link: `[[Page name#Section name|displayed text]]`  as an example. 

`[[Ledger\|NAME]]` from your example pointing to a page `Ledger|NAME` instead of `Ledger`

**Comment by theSiberman** [comment]
Hey Mate,

Still no dice for me after updating...
![image](https://user-images.githubusercontent.com/3615840/127267388-4abbdbba-91cf-4647-921b-fcf69e33eb54.png)

**Comment by tgrosinger** [comment]
@theSiberman Please make sure you are using one of the default themes and have no custom css snippets enabled. It appears to me that the links are not using a mono-space font, and that might be caused by your theme.

For reference here's what it looks like in my test Vault with all the default settings:

![image](https://user-images.githubusercontent.com/597386/127338865-530ab530-70c5-48f4-a5f2-529d5c1a08f1.png)

**Comment by theSiberman** [comment]
Hey mate,

Yep, that fixed it, I was using a theme called “cybertron”

Thanks!
