### ISSUE TITLE
Transposing tables

### ISSUE THREAD

**Issue by jeLee6gi** [tgrosinger/advanced-tables-obsidian#73]
**Is your feature request related to a problem? Please describe.**
Sometimes you notice that a table would work better if it was transposed, e.g. it becomes too wide.

**Describe the solution you'd like**
A button which transposes the current table.

**Comment by jeLee6gi** [comment]
The only problem I see is that per column text alignment could not be preserved so it would not be reversible, but I would be ok with transpose resetting text alignment.

**Comment by tgrosinger** [comment]
@jeLee6gi, this is an interesting suggestion however it is not currently supported by the underlying library which powers this plugin. I'm going to close this issue, but if pull requests are welcome if you would like to work on adding this functionality to the [md-advanced-tables library](https://github.com/tgrosinger/md-advanced-tables).

**Comment by mochsner** [comment]
@tgrosinger Did development on the underlying library for this a while ago, happy to revisit. Any issues with the code in particular? I recall it was my first time with typescript, so I'm happy to optimize or improve readability in any way.

**Comment by ooker777** [comment]
For now every time I need to transpose table, I visit https://www.tablesgenerator.com
