### ISSUE TITLE
Cycle through alignment options

### ISSUE THREAD

**Issue by Ampa** [tgrosinger/advanced-tables-obsidian#74]
At present there are 3 keyboard bindings for align column left/center/right.

Would you consider an additional binding that cycles through the alignments?

Left > Center > Right > (back to left)

That way I only need remember a single key press, and can rapidly try alignments to see what looks best.

Thanks.

**Comment by tgrosinger** [comment]
Hi @Ampa, thanks for the suggestion.
I think this plugin already has too many keyboard shortcuts, so at this time I am not planning on adding additional ones.

You can use the toolbar pane though to avoid needing to remember so many shortcuts. It can be opened with the button in the ribbon.

**Comment by Ampa** [comment]
Thanks for considering the suggestion.

I understand your reasoning - there are indeed many existing shortcuts!

The ribbon certainly removes the need to remember shortcuts, but means taking hands off the keyboard.
Also with the new design (as a panel rather than a toolbar) I have not found anywhere convenient to put it!
