### ISSUE TITLE
Sort table by number

### ISSUE THREAD

**Issue by ruohuchengxhe** [tgrosinger/advanced-tables-obsidian#75]
Hi! 
Thanks for developing such a useful tool!
I use tables with multiple number columns, such as year numbers, is it possible to sort by these numbers? 
Thanks!

**Comment by tgrosinger** [comment]
@ruohuchengxhe, the plugin only supports sorting by a single column. To sort the table, place your cursor in the column by which you wish to sort, then press one of the sort buttons in the Advanced Tables toolbar or use the Command Palette to select one of the sort options.

**Comment by ruohuchengxhe** [comment]
> @ruohuchengxhe, the plugin only supports sorting by a single column. To sort the table, place your cursor in the column by which you wish to sort, then press one of the sort buttons in the Advanced Tables toolbar or use the Command Palette to select one of the sort options.

Thanks for your reply!
I wonder if it is able to sort by numbers?
For example, I have  12, 1,  3, 6  in a column, when I sort, I will get 1, 12, 3, 6 instead of 1, 3, 6, 12.
Many thanks!

**Comment by tgrosinger** [comment]
Ahh, I understand what you are asking now. I do not believe that will work in the current state.

**Comment by ruohuchengxhe** [comment]
> Ahh, I understand what you are asking now. I do not believe that will work in the current state.

I see. Thanks anyways. Hope it is possible in future.

**Comment by tgrosinger** [comment]
Added in 0.12.1

**Comment by ruohuchengxhe** [comment]
> Added in 0.12.1

👍    💕    👏
