### ISSUE TITLE
Only working when cursor is in first / left / index=0 pane

### ISSUE THREAD

**Issue by luckman212** [tgrosinger/advanced-tables-obsidian#82]
**Describe the bug**
Typical layout might be split pane, Edit on left and Preview on right. This is how I usually work, and probably many others. BUT, if this gets reversed (preview left, edit right) strange things happen with Advanced Tables.

**To Reproduce**
1. Put edit pane on left
2. Make a new table
3. Start mucking around with it
4. Swap preview & edit panes.
5. Muck some more... 
6. It's broken

**Expected behavior**
Functions should work regardless of pane configuration.

**Video**

https://user-images.githubusercontent.com/1992842/115970530-ebdb2700-a510-11eb-9c81-a9d07f330486.mp4

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - Obsidian Version: 0.12.1
 - Advanced Tables Version: 0.12.2

**Comment by luckman212** [comment]
One more example

https://user-images.githubusercontent.com/1992842/115970631-a1a67580-a511-11eb-85a0-3ba5879b5715.mp4

**Comment by awalvie** [comment]
Yup, facing the same issue as well.

**Comment by lgyz** [comment]
me too.

**Comment by tgrosinger** [comment]
Hmm, this is a tricky one. I'm having trouble reproducing this behavior. I did once get it to not delete the right row, but otherwise it's behaving normally no matter how many panes are open.

I'll try to dig into this more.

**Comment by tgrosinger** [comment]
Yes, I am trying it from a pane one the right (if two or three panes) or middle (if three panes).

**Comment by luckman212** [comment]
@tgrosinger thanks for looking. Hmm, so weird because for me this is so simple to reproduce every time. I wonder what's different about our environments?

For testing purposes, I created a brand new vault with ZERO customizations or plugins. All I did was disable Safe Mode, install AT (ver 0.12.3) and created a couple of test notes. See linked video (sorry it's a bit long, I am posting some annotations below if you want to just skip to the bugged parts).

> **0:29** - nothing happens when delete column button is pressed
> 
> **0:38** - after leaving and returning to the note, delete column button errors that we're not in a table cell (we are)
> _(variations of this continue thru ~1:19)_
>
> **1:36-1:38** - shows nonworking vs working behavior when editing in right vs left pane
>
> **2:05-2:32** - shows odd behavior where clicking 'delete column' actually deletes a cell's contents instead, and also does something strange to the editor where the left vs right panes no longer have the same buffer content even though they are linked
>
> **2:37-2:54** - clicking 'delete row' (on 'dog') deletes the wrong data (seems to delete TWO rows below and leave a blank row) and again causes the buffer to be inconsistent between all linked panes
>
> **3:08-3:19** - clicked 'delete row' and TWO rows are deleted
>
> **3:44-4:00** - more nonfunctional AT toolbar clicks, no errors in Console or Notice toasts
>
> **4:06** - delete row again deleting 2 rows of data plus the word "Hello" which lies OUTSIDE of the table, and causing left pane to go out of sync
>
> **5:08** - pressing 'insert row' also deletes a row (bottom row) of data

video (too large for GitHub issues): https://dsc.cloud/b854da/CleanShot-2021-05-03-at-08.53.02.mp4

**Comment by luckman212** [comment]
Just an update, I just re-tested this with the newly-minted Obsidian 0.12.2. Was hoping this was a weird upstream thing (which it still might be!) but—still bugged.

**Comment by luckman212** [comment]
@tgrosinger Sorry to be a nag. 😞
Is there anything I can do to help track this down? I am assuming it's something to do with [this commit](https://github.com/tgrosinger/advanced-tables-obsidian/commit/d42b0da31d4ab208a39c2e56b888f77ac1d32938) (Update to new Obsidian Editor interface)

**Comment by tgrosinger** [comment]
I managed to reproduce this. It appears that it will work when running commands from the command palette. It's just the toolbar that is incorrect because it is caching a reference to the editor.

I'll get a fix out for this shortly.

**Comment by tgrosinger** [comment]
Thanks for all your help tracking this down @luckman212

**Comment by luckman212** [comment]
Beautiful!  Thank you @tgrosinger for this fix. Just loaded it up and confirmed that it's working perfectly now. Enjoy the coffees! ☕
