### ISSUE TITLE
Ill rendered varphi

### ISSUE THREAD

**Issue by RobertoHRO** [tgrosinger/advanced-tables-obsidian#83]
**Describe the bug**
Inside a table the letter φ is shows up as ϕ. Interestingly, if you copy and paste the incorrectly rendered letter outside the table, it is rendered correctly. Maybe the font has a problem here?

**To Reproduce**

Paste this nicely formatted table into md file, open it with obsidian - and see 'ϕ, ϕ'.

```
|         |      |     |         |      |     |
| ------- | ---- | --- | ------- | ---- | --- |
| alpha   | α    | A   | nu      | ν    | N   |
| beta    | β    | B   | xi      | ξ    | Ξ   |
| gamma   | γ    | Γ   | omicron | ο    | Ο   |
| delta   | δ    | Δ   | pi      | π, ϖ | Π   |
| epsilon | ϵ, ε | E   | rho     | ρ, ϱ | P   |
| zeta    | ζ    | Z   | sigma   | σ, ς | Σ   |
| eta     | η    | H   | tau     | τ    | T   |
| theta   | θ, ϑ | Θ   | upsilon | υ    | Υ   |
| iota    | ι    | I   | phi     | φ, ϕ | Φ   |
| kappa   | κ, ϰ | K   | chi     | χ    | X   |
| lambda  | λ    | Λ   | psi     | ψ    | Ψ   |
| mu      | μ    | M   | omega   | ω    | Ω   |
```

**Expected behavior**
It should be 'φ, ϕ'.

**Screenshots**
How Obsidian renders the table
![grafik](https://user-images.githubusercontent.com/25647024/115993307-82bbe800-a5d2-11eb-89a4-47c4b276cf6f.png)

How notepad++ does:
![grafik](https://user-images.githubusercontent.com/25647024/115993344-9ff0b680-a5d2-11eb-8cbb-c998d11af2cc.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Obsidian Version:0.11.13
 - Advanced Tables Version: 0.12.2

**Comment by tgrosinger** [comment]
I believe this is an issue in obsidian, not in Advanced Tables. I tested this in Obsidian with the Advanced Tables plugin disabled and got the same results.

Please send this issue to the Obsidian team via the [forums](https://forum.obsidian.md). Thank you.
