### ISSUE TITLE
[Question] How to have multiple lines in a cell?

### ISSUE THREAD

**Issue by andrewcrook** [tgrosinger/advanced-tables-obsidian#86]
This might be a daft question but how do you get multiple lines in a cell?

**Comment by tgrosinger** [comment]
@andrewcrook, Obsidian tables do not support multiple lines in a single row. Please see #54.

**Comment by andrewcrook** [comment]
@tgrosinger 
> @andrewcrook, Obsidian tables do not support multiple lines in a single row. Please see #54.

Thanks for getting back to me

**Comment by andrewcrook** [comment]
> @andrewcrook, Obsidian tables do not support multiple lines in a single row. Please see #54.

@tgrosinger  thanks for the reply 
is this because of a limitation of Obsidian or md-advanced-tables ?

**Comment by tgrosinger** [comment]
This is a limitation of the markdown spec. In markdown, each line corresponds with one row in the table.

**Comment by andrewcrook** [comment]
> This is a limitation of the markdown spec. In markdown, each line corresponds with one row in the table.

Got it. Thanks
