### ISSUE TITLE
long line stuggle : Misalignement

### ISSUE THREAD

**Issue by Mara-Li** [tgrosinger/advanced-tables-obsidian#87]
**Describe the bug**
The plugin seems to have some problem with long line, mainly if we activate `white-space` in css, because long line bug on obsidian with table. 

**To Reproduce**
1. Have this css 
```css
.cm-s-obsidian .HyperMD-table-row {
    white-space: normal;
}
```
2. Create a long table
3. Tabulation, after this long line.

**Expected behavior**
The `|` take the entire line.

**Screenshots**
Actually : 
![image](https://user-images.githubusercontent.com/30244939/116808630-29a40500-ab3a-11eb-8edd-d09b772ddb6b.png)
(preview : 
![image](https://user-images.githubusercontent.com/30244939/116808635-3163a980-ab3a-11eb-9289-9d40b67c547b.png))

Idea to align : 
![image](https://user-images.githubusercontent.com/30244939/116808822-24938580-ab3b-11eb-8efe-bfdf37839c08.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version: [e.g. v0.9.10] (Settings → About → Current Version) v0.12.1
 - Advanced Tables Version: [e.g. 0.4.0] (Settings → Third-party plugin → Browse → Advanced Tables → currently installed) 0.12.3

**Additional context**
/

**Comment by tgrosinger** [comment]
Hi Mara-Li,
I do not understand your suggestion for how to align. Can you please provide more detail?

**Comment by Mara-Li** [comment]
I think it would be good to have the `|` on the "last line" and not "necessarily" aligned with the location (in the sense that it would avoid having multiple lines of `---`). Also, I noticed that the plugin has a really hard time creating a new row when there are several lines in it:

![image](https://user-images.githubusercontent.com/30244939/116877620-79f49300-ac1e-11eb-9062-587a3f2b1b9c.png)
![image](https://user-images.githubusercontent.com/30244939/116877624-7a8d2980-ac1e-11eb-92b4-31a9371ab9a9.png)

(sorry, English is not my primary language So I have some difficulty to explain a possible solution ^^")

**Comment by tgrosinger** [comment]
@Mara-Li, I believe the plugin is working as expected it is just very hard to tell because of the lines wrapping. If the `|` were placed somewhere else, then it would be in the wrong location and not actually at the end of the line.

Unfortunately Markdown just does not have a great way of handling long rows in tables.

I'm going to close this out because I don't think there's any action we can take here.
