### ISSUE TITLE
table format in editor mode

### ISSUE THREAD

**Issue by caHerrera100** [tgrosinger/advanced-tables-obsidian#89]
**Describe the bug**
width of table cells not symmetrical in editor mode

**To Reproduce**
1. Enable setting which matches cells width to the cell of the widest width
1. Enter | to begin table, create a table with tab, etc. 

**Expected behavior**
When tab is clicked, the table produces cells that are matched with the cell creating a nice and readable display such as the demo

**Screenshots**
![Screen Shot 2021-05-13 at 3 03 17 PM](https://user-images.githubusercontent.com/82972553/118193339-5d194600-b3fc-11eb-8223-7795e6fbafd6.png)

Preview mode appears fine:
![Screen Shot 2021-05-13 at 3 03 46 PM](https://user-images.githubusercontent.com/82972553/118193381-6d312580-b3fc-11eb-9ab9-c0ebdd17a099.png)

**Desktop (please complete the following information):**
 - Mac OS: Big Sur v11.3.1
 - Obsidian Version: 0.12.3
 - Advanced Tables Version: 0.12.4

**Comment by tgrosinger** [comment]
It looks like you are not using a monospaced font when in edit mode. Do you have custom styles or a custom theme that would be changing that?

**Comment by caHerrera100** [comment]
Hi @tgrosinger, I believe that was the issue! Thank you for the prompt response! The plugin is an awesome addition to Obsidian
