### ISSUE TITLE
Support remark style tables

### ISSUE THREAD

**Issue by ngirard** [tgrosinger/advanced-tables-obsidian#9]
Using: Table editor 0.3.2 / Obsidian 0.9.10 / Ubuntu 20.04.

Using this test table:
```md
HA | HB
--- | ---
Aaaaaaaaaa | Baaaaaaaaaaa
```

Selecting `Format table at the cursor` from the command palette does nothing.
I found no relevant message in the console.

**Comment by tgrosinger** [comment]
@ngirard, can you check if "Pad cell width using spaces" is enabled in the Table Editor settings? If that is **not** selected, then the table you provided is exactly what I would expect to see.

<img width="842" alt="table-editor-settings-page" src="https://user-images.githubusercontent.com/597386/97781513-345ced80-1b49-11eb-83f4-f16c437ae3fe.png">

**Comment by ngirard** [comment]
> can you check if "Pad cell width using spaces" is enabled in the Table Editor settings?

Hey @tgrosinger, 
I just checked and it's enabled.

Cheers

**Comment by tgrosinger** [comment]
Hmm, and just to be thorough, can you please make sure your cursor is within a cell of the table when running the command? Similarly, if you put your cursor in the cell "Aaaaaaaaaa" and press tab, does anything happen?

If the answer is still no, can you please turn on verbose logs and paste the results?

Thank you

<img width="842" alt="verbose-logs" src="https://user-images.githubusercontent.com/597386/97782513-172b1d80-1b4f-11eb-84d9-8b9eb8dd26bc.png">

**Comment by ngirard** [comment]
> just to be thorough, can you please make sure your cursor is within a cell of the table when running the command?

It's the case.

> if you put your cursor in the cell "Aaaaaaaaaa" and press tab, does anything happen?

Nothing happens but the regular behaviour associated with the tab key.

> If the answer is still no, can you please turn on verbose logs and paste the results?

Both hitting tab and triggering "Format table" just produce
```
text-editor-interface.ts:20 getCursorPosition was called
text-editor-interface.ts:44 acceptsTableEdit was called on row 4
text-editor-interface.ts:50 getLine was called on line 4
```

**Comment by tgrosinger** [comment]
Ohh, I think I just realized the issue!

Markdown tables need to have pipe characters on the outside. Can you give this one a shot?

```
| HA | HB |
| --- | --- |
| Aaaaaaaaaa | Baaaaaaaaaaa |
```

**Comment by ngirard** [comment]
Hey @tgrosinger, you nailed it !
This was the reason for the unexpected behaviour.
Using your proposed syntax, Table editor behaves just fine.

Now, given that the Obsidian documentation explicitly allows the syntax I used (I'm sure it can be found online, but the related file within the help vault is called `How to/Format your notes.md`), would you mind adapting your parser ?

**Comment by tgrosinger** [comment]
Oh really? Well that is good to know. I wonder what flavor of Markdown they are using. There are unfortunately a different versions and tables are not completely standardized like some features are.

I need to update the underlying engine ([mte-kernel](https://github.com/tgrosinger/mte-kernel)) in order to add that new format. I didn't write this code, but I do have plans on making some changes and extending it a bit. So I am not going to be able to do that right away, but I will leave this ticket here and as soon as I learn where that change needs to go, I'll get it working.

**Comment by tgrosinger** [comment]
Sounds like Obsidian is using https://github.com/remarkjs/remark to parse the markdown.

**Comment by ngirard** [comment]
Yeah, it the wild west with all these implementations. Even CommonMark couldn't come to a sane proposal with tables.

Well good luck with the nitty-gritty details, I'm not in a rush !

**Comment by tgrosinger** [comment]
It looks like the [Obsidian Prettify plugin](https://github.com/cristianvasquez/obsidian-prettify) will convert tables in this format into the format needed by this plugin.

I am going to suggest using that plugin to reformat your table as the recommended solution to this problem.
