### ISSUE TITLE
Table in list items not working right

### ISSUE THREAD

**Issue by ramGHnet** [tgrosinger/advanced-tables-obsidian#91]
**Describe the bug**
Add a table to a list item doesn't work right

**To Reproduce**
Create the following list items with tables
1. dummy1 (works but ==not aligned right==)

| col1  | col2  |
| ----- | ----- |
| works | works |

2. dummy 2 (==doesn't work== but aligned right)

	| col1               | col2               |
	| ------------------ | ------------------ |
	| doesn't work right | doesn't work right | 

**Expected behavior**
Advanced Table should work with both tables in the example above

**Screenshots**
[2021-05-18-10-43-32.jpg](https://postimg.cc/Lh4CqXfr)

**Desktop (please complete the following information):**
 - OS: macOS 11.3.1
 - Obsidian Version: 0.12.3
 - Advanced Tables Version: 0.12.4

**Additional context**

**Comment by tgrosinger** [comment]
Sounds like it's not detecting tables when they are indented. Thanks for the issue report. I'll take a look.

**Comment by tgrosinger** [comment]
Ah interesting. It looks like this plugin is actually working correctly in the indented table. What is not working is switching to a monospace font when the table is indented. This is an Obsidian bug. I've mentioned it in discord (https://discord.com/channels/686053708261228577/716028884885307432/913578982081978409)
