### ISSUE TITLE
Automatically determine RENDERED column width from column contents.

### ISSUE THREAD

**Issue by swehba** [tgrosinger/advanced-tables-obsidian#93]
**Is your feature request related to a problem? Please describe.**
Not really a problem, per se. As it currently works, it looks like Advanced Tables does not specify any information about column width. That being the case, all columns are rendered at the same width. This does not work well when some columns have narrow content and others have wider content.

I should note that I am suggesting how the table should render in preview, not how it displays in edit mode. In edit mode, the column widths are correctly calculated based on the longest value in any cell in a column.

**Describe the solution you'd like**
When Advanced Tables renders a table, iterate through the content of all cells in each column and determine the average length of the cells in that column. The add column width attributes to the table HTML based on those widths. For example, say the longest entry in column 1 is 10 characters, 20 characters in column 2, and 30 characters in column three. Render the  table so that column 1 is 16% the total table width (10 / (10 + 20 + 30)), column 2 is 33%, and column 3 is 50%.

**Describe alternatives you've considered**
I have tried manually editing the HTML that is generated, but that doesn't stick. It is refreshed whenever the page is saved.

**Additional context**

**Comment by tgrosinger** [comment]
Thank you for your suggestion.
The Advanced Tables plugin does not have any control over how tables are rendered. It is only able to affect the editable contents of the table.
