### ISSUE TITLE
Floating toolbar not there anymore?

### ISSUE THREAD

**Issue by neurosock** [tgrosinger/advanced-tables-obsidian#94]
**Describe the bug**
For several weeks the plugin does not show anymore the floating table tools, but just the panel. Disabling in settings the panel does not help. 

**To Reproduce**
1. Make table
2. Press Ctrl+Shit+D

**Expected behavior**
Show little floating toolbar

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version: 0.12.4
 - Advanced Tables Version: 0.12.5

**Additional context**
Was this removed or is it just me? The floating toolbar was quite handy.
Thanks for the great work!

**Comment by tgrosinger** [comment]
Hello,
The toolbar has been moved in to a small sidebar window. It can be opened with the ribbon icon or with the keyboard shortcut.

![image](https://user-images.githubusercontent.com/597386/121702550-d69d6600-ca86-11eb-8ce1-ef92edfca539.png)

**Comment by Write** [comment]
Any chance to get the floating table tools back ? I loved it

**Comment by Interpause** [comment]
Was there an obsidian update that made the floating toolbar infeasible? I think it would be a better UI experience on mobile compared to the sidebar which takes up the entire screen.

**Comment by nhan000** [comment]
I'd very much like to have the floating toolbar.

But if it's not practical, do you mind updating the GIF in the readme doc? I spent the last 30 min hunting for this toolbar.
