### ISSUE TITLE
How do I delete columns?

### ISSUE THREAD

**Issue by rajlego** [tgrosinger/advanced-tables-obsidian#95]
I might be doing something stupid but I can't figure out how to delete columns. I'm on the latest version of advanced tables installed from the community plugin system on windows 10.

**Comment by tgrosinger** [comment]
To delete a column, place your cursor in a cell within the column to be deleted and use the underlined button in the toolbar:

![image](https://user-images.githubusercontent.com/597386/122660760-a44fd080-d138-11eb-8a6f-76075484803e.png)

If you do not see the toolbar, you can open it with the Advanced Tables button in the sidebar ribbon:

![image](https://user-images.githubusercontent.com/597386/122660780-dfea9a80-d138-11eb-92f0-4a8a07931678.png)
