### ISSUE TITLE
Cannot Export to CSV

### ISSUE THREAD

**Issue by richardlm** [tgrosinger/advanced-tables-obsidian#96]
The Export to CSV button produces a pop-up with the table inside it but not clear what to do to actually export it as CSV.

1. Create a table
2. Place cursor in table
3. Click on the 'CSV' icon
4. Pop-up appears containing table contents, but no 'export' button...?

I would expect an 'export' button on the pop-up, or for 'enter' to activate the export and prompt where to save.

Windows 10
Obsidian Version: 0.12.6
Advanced Tables Version: 0.12.5

Note that this may not be a bug, just a user error!

![image](https://user-images.githubusercontent.com/15072925/123070386-9d141580-d40b-11eb-8b36-04b358f247cd.png)

**Comment by tgrosinger** [comment]
@richardlm, you can copy and paste the values in that popup into another program or file. For example, if you saved that in a text file and named it data.csv, then open it with Excel, it would be able to understand your table.

Let me know if that helps.

**Comment by richardlm** [comment]
Ah, didn't realise it was a simple as that! Many thanks for the quick response - and the very useful plugin.
