### ISSUE TITLE
Columns Incorectly Sized With Inline Footnotes

### ISSUE THREAD

**Issue by bm751613** [tgrosinger/advanced-tables-obsidian#98]
**Describe the bug**
When using Obsidian's native footnote notation, columns are no longer correctly sized. This appears to be due to Obsidian changing the reference to superscript.

**To Reproduce**
Create a table with a footnote reference (eg. [^1])

**Expected behavior**
Columns should remain inline after a <tab> or <enter>.

**Screenshots**
![image](https://user-images.githubusercontent.com/7523158/125280349-f375c500-e2e2-11eb-816d-9b5b21f0ac31.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version: v0.12.10
 - Advanced Tables Version: v0.12.5

**Comment by tgrosinger** [comment]
This is because footnotes are given a smaller font size in Obsidian. You could "fix" this with a CSS snippet that makes footnotes full size again. Though I don't think it's a great solution.

```css
.cm-footref {
    font-size: 1em !important;
}
```

Unfortunately there is a not a lot else that I can do as the number of characters is being set correctly.
