### ISSUE TITLE
[Question] can I add a checkbox in a cell?

### ISSUE THREAD

**Issue by Antoine-lb** [tgrosinger/advanced-tables-obsidian#99]
Hello 👋
Is it possible to put a checkbox in a cell so that when I put the document in reading mode (not morkdown) I can check the boxes inside of the table cell?
I don't know if is not possible or I'm doing it wrong.

Anyways, grate plugin, love it.

**Comment by tgrosinger** [comment]
Hi @Antoine-lb,
It does not appear that Obsidian will render a checkbox in a table cell. This is outside of the control of this plugin, as this plugin is only affecting the editing of tables and not their rendering.

Thank you.

**Comment by dawidmachon** [comment]
Create checkbox below table and make it embed: ![[#^ref]]
